### 캐글 제출용

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
!gdown https://drive.google.com/uc?id=1j4lPOBinj9hgHFrUIYw6-6I1ZYqjTe4W
!gdown https://drive.google.com/uc?id=1-3X_0Wj2GnvSDKg_4N1HjIl_vcW7hKDu

/bin/bash: gdown https://drive.google.com/uc?id=1j4lPOBinj9hgHFrUIYw6-6I1ZYqjTe4W: No such file or directory
/bin/bash: gdown https://drive.google.com/uc?id=1-3X_0Wj2GnvSDKg_4N1HjIl_vcW7hKDu: No such file or directory


In [6]:
from google.colab import drive

# 구글 드라이브 마운트
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
path = '/content/drive/MyDrive/KT aivleschool/KT_aivle_school_AI_track/15. MINI_PJ5/Kaggle/'

In [131]:
data = pd.read_csv(path + 'train_dataset.csv')
test = pd.read_csv(path + 'test_dataset.csv')

In [133]:
import re
data = data.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

In [11]:
data.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyGyro-min()-Y  \
5876                 0.419680  ...          -0.997983   
5877                -0.260559  ...          -0.951267   
5878                 0.155540  ...          -0.998177   
5879                -0.229386  ...          -0.687973   
5880                 0.505829  ...          -0.906829   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
5876                        -0.999967                  -0.987428   
5877                        -0.982422                  -0.561358   
5878                        -0.999920                  -0.989684   
5879                        -0.940509                  -0.465531   
5880                        -0.997315                  -0.979258   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
5876                      -1.000000                -0.981119   
5877                       0.241367                -0.415217   
5878                      -1.000000                -0.991452   
5879                       0.323401                -0.504324   
5880                      -1.000000                -0.949917   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
5876                   -0.983765                         0.052914   
5877                   -0.845447                         0.325461   
5878                   -0.989032                         0.362439   
5879                   -0.867993                         0.031915   
5880                   -0.988100                         0.463038   

      angle(tBodyAccMean,gravity)          Activity  Activity_dynamic  
5876                    -0.034888           SITTING                 5  
5877                     0.721718  WALKING_UPSTAIRS                 1  
5878                     0.060173            LAYING                 3  
5879                     0.260880  WALKING_UPSTAIRS                 1  
5880                     0.107690           SITTING                 5  

[5 rows x 52 columns]

In [51]:
test.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
1466          -0.106398               -0.081939                0.185382   
1467          -0.109078               -0.191660                0.252811   
1468          -0.121377                0.190174               -0.004620   
1469          -0.116644                0.103635                0.263890   
1470          -0.083858                0.183636               -0.218482   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
1466               0.071741               0.009478   
1467               0.075298               0.007827   
1468               0.282992              -0.166026   
1469               0.089082              -0.006599   
1470              -0.030629              -0.084982   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
1466                    0.019718                    0.246692   
1467                    0.218177                    0.220255   
1468                    0.282091                   -0.016718   
1469                    0.335221                    0.083270   
1470                    0.041531                   -0.309509   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
1466                    0.370205                    0.002332   
1467                    0.243859                    0.323898   
1468                    0.446784                   -0.189417   
1469                    0.160313                    0.504003   
1470                    0.180688                   -0.209794   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
1466                 0.232695  ...                           -0.999736   
1467                 0.106566  ...                           -0.999414   
1468                -0.223721  ...                           -0.703363   
1469                -0.073582  ...                           -0.999296   
1470                -0.009915  ...                           -0.895324   

      fBodyAccJerk-bandsEnergy()-49,64.2  fBodyGyro-min()-Y  \
1466                           -0.999642          -0.993454   
1467                           -0.999498          -0.999391   
1468                           -0.260255          -0.793648   
1469                           -0.998998          -0.954967   
1470                           -0.884323          -0.799233   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
1466                        -0.999949                  -0.988987   
1467                        -0.999986                  -0.996189   
1468                        -0.771367                  -0.120213   
1469                        -0.999361                  -0.945335   
1470                        -0.927293                   0.076213   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
1466                      -1.000000                -0.993440   
1467                      -1.000000                -0.998003   
1468                       0.711324                -0.110976   
1469                      -0.798901                -0.946530   
1470                       0.710326                -0.361945   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
1466                   -0.995521                         0.166124   
1467                   -0.994214                         0.425059   
1468                   -0.553784                         0.187655   
1469                   -0.954411                        -0.200412   
1470                   -0.813583                         0.032252   

      angle(tBodyAccMean,gravity)  
1466                    -0.054788  
1467                     0.076333  
1468                     0.330378  
1469                    -0.048474  
1470                     0.374865  

[5 rows x 50 columns]

## 데이터 전처리

In [135]:
def target_morphs(data, target = None, target_dynamic = None):
    df = data.copy()
    # target이 지정되지 않았으면 가장 마지막 열로 지정
    if target is None:
        target = data.columns[-1]
    # targets가 존재하지만 리스트가 아니라면 리스트로 변경
    if target_dynamic is not None:
        if not isinstance(target_dynamic, list):
            target_dynamic = [target_dynamic]
        # target이 targets에 포함되는지 여부를 target에 저장
        df[target] = df[target].apply(lambda x: 0 if x in target_dynamic else 1)
    return df

In [30]:
data.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyGyro-min()-Y  \
5876                 0.419680  ...          -0.997983   
5877                -0.260559  ...          -0.951267   
5878                 0.155540  ...          -0.998177   
5879                -0.229386  ...          -0.687973   
5880                 0.505829  ...          -0.906829   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
5876                        -0.999967                  -0.987428   
5877                        -0.982422                  -0.561358   
5878                        -0.999920                  -0.989684   
5879                        -0.940509                  -0.465531   
5880                        -0.997315                  -0.979258   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
5876                      -1.000000                -0.981119   
5877                       0.241367                -0.415217   
5878                      -1.000000                -0.991452   
5879                       0.323401                -0.504324   
5880                      -1.000000                -0.949917   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
5876                   -0.983765                         0.052914   
5877                   -0.845447                         0.325461   
5878                   -0.989032                         0.362439   
5879                   -0.867993                         0.031915   
5880                   -0.988100                         0.463038   

      angle(tBodyAccMean,gravity)          Activity  Activity_dynamic  
5876                    -0.034888           SITTING                 5  
5877                     0.721718  WALKING_UPSTAIRS                 1  
5878                     0.060173            LAYING                 3  
5879                     0.260880  WALKING_UPSTAIRS                 1  
5880                     0.107690           SITTING                 5  

[5 rows x 52 columns]

In [61]:
y = data[['Activity', 'Activity_dynamic']]
y

Activity  Activity_dynamic
0               STANDING                 4
1                 LAYING                 3
2               STANDING                 4
3                WALKING                 0
4     WALKING_DOWNSTAIRS                 2
...                  ...               ...
5876             SITTING                 5
5877    WALKING_UPSTAIRS                 1
5878              LAYING                 3
5879    WALKING_UPSTAIRS                 1
5880             SITTING                 5

[5881 rows x 2 columns]

In [136]:
target_morphs(data, 'Activity', ['STANDING', 'LAYING', 'SITTING'])

tBodyAccmeanZ  tBodyAccarCoeffX2  tBodyAccarCoeffY1  tBodyAccJerkmeanX  \
0         -0.103362          -0.094784          -0.109208           0.068584   
1         -0.098163          -0.052478           0.464764           0.075947   
2         -0.108717          -0.226718           0.301165           0.079530   
3         -0.150354           0.549363          -0.384117          -0.309509   
4          0.091229          -0.091537          -0.610793           0.584212   
...             ...                ...                ...                ...   
5876      -0.131974          -0.059080           0.000441           0.082392   
5877      -0.105174           0.275170          -0.191391          -0.108297   
5878      -0.107440          -0.025156           0.407618           0.070742   
5879      -0.121001           0.686123          -0.606018          -0.085843   
5880      -0.138018          -0.275424          -0.158631           0.079556   

      tBodyAccJerkmeanY  tBodyAccJerkarCoeffX2  tBodyAccJerkarCoeffY1  \
0             -0.014314               0.198600              -0.073666   
1              0.004456               0.130310               0.401913   
2              0.014504               0.111340               0.263556   
3             -0.201293               0.411714              -0.372620   
4             -0.266815              -0.248696              -0.628852   
...                 ...                    ...                    ...   
5876          -0.008733               0.180157               0.041011   
5877           0.050577               0.168315              -0.313497   
5878           0.011347               0.222424               0.259452   
5879          -0.039197               0.499451              -0.628068   
5880          -0.119456               0.027651              -0.051177   

      tBodyAccJerkarCoeffY3  tBodyAccJerkarCoeffZ1  tBodyGyroarCoeffZ3  ...  \
0                  0.113098              -0.058315            0.354270  ...   
1                  0.512569               0.011987            0.503466  ...   
2                  0.562730               0.314589            0.132061  ...   
3                  0.288349              -0.259441           -0.711894  ...   
4                  0.095282              -0.240501           -0.305964  ...   
...                     ...                    ...                 ...  ...   
5876               0.173103              -0.001160            0.419680  ...   
5877              -0.067457              -0.006740           -0.260559  ...   
5878               0.497603               0.187073            0.155540  ...   
5879               0.337687              -0.037529           -0.229386  ...   
5880               0.118587               0.160995            0.505829  ...   

      fBodyGyrominY  fBodyGyrobandsEnergy49641  fBodyBodyAccJerkMagiqr  \
0         -0.996607                  -0.999969               -0.985141   
1         -0.992681                  -0.999941               -0.988982   
2         -0.999971                  -0.999976               -0.991535   
3         -0.876509                  -0.969331               -0.387366   
4         -0.960097                  -0.990292               -0.220963   
...             ...                        ...                     ...   
5876      -0.997983                  -0.999967               -0.987428   
5877      -0.951267                  -0.982422               -0.561358   
5878      -0.998177                  -0.999920               -0.989684   
5879      -0.687973                  -0.940509               -0.465531   
5880      -0.906829                  -0.997315               -0.979258   

      fBodyBodyAccJerkMagentropy  fBodyBodyGyroMagmean  \
0                      -1.000000             -0.975435   
1                      -1.000000             -0.978534   
2                      -1.000000             -0.991953   
3                       0.323260             -0.479590   
4                       0.446385        

In [137]:
from sklearn.metrics import classification_report, confusion_matrix

def score_model(data, random_state = None):
    X, y, lb = data_processing(data)
    x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = random_state)
    print('='*150)
    y_pred = double_model(x_train, y_train, x_test)
    print(classification_report(y_test['Activity_dynamic'], y_pred))
    print('='*150)
    # 썼던 라벨(lb)가 주어진다면
    if lb is not None:
        # LabelEncoder가 숫자형 범주로 바꾸는데 사용한 class들을 가져오고
        values = lb.classes_
        # 그걸 다시 LabelEncoder를 이용해 숫자로 바꿔서
        keys = lb.transform(lb.classes_)
        # 재결합해서 번역 Dict 생성
        dictionary = dict(zip(keys, values))
        for _ in range(len(dictionary)):
            # 그래서 Confusion Matrix를 보기 쉽게 출력
            print(dictionary[_], end=', ')
    print()
    print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


In [138]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

def data_processing(data, target = 'Activity'):
    # target_dynamic 리스트에 들어있는 Activity는 0, 없으면 1
    df = target_morphs(data, target = target, target_dynamic = ['STANDING', 'LAYING', ' SITTING'])
    # Unused
    # ynum = len(lb.classes_)
    # 위의 is dynamic이 아닌 실제 값. morphs는 Activity를 덮어씌우게 만들어서 이렇게 따로 추가해 줘야 함.
    real_y = data['Activity_dynamic'].copy()
    # Activity_dynamic 에 저장
    df[f'{target}_dynamic'] = real_y
    target = [target, f'{target}_dynamic']
    X = df.drop(target, axis = 1)
    y = df[target]
    # lb를 반환하는 이유는 score_model에서
    return X, y, lb
X, y, lb = data_processing(data)
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 2023)

In [42]:
X

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
0             -0.103362               -0.094784               -0.109208   
1             -0.098163               -0.052478                0.464764   
2             -0.108717               -0.226718                0.301165   
3             -0.150354                0.549363               -0.384117   
4              0.091229               -0.091537               -0.610793   
...                 ...                     ...                     ...   
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
0                  0.068584              -0.014314   
1                  0.075947               0.004456   
2                  0.079530               0.014504   
3                 -0.309509              -0.201293   
4                  0.584212              -0.266815   
...                     ...                    ...   
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
0                       0.198600                   -0.073666   
1                       0.130310                    0.401913   
2                       0.111340                    0.263556   
3                       0.411714                   -0.372620   
4                      -0.248696                   -0.628852   
...                          ...                         ...   
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
0                       0.113098                   -0.058315   
1                       0.512569                    0.011987   
2                       0.562730                    0.314589   
3                       0.288349                   -0.259441   
4                       0.095282                   -0.240501   
...                          ...                         ...   
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
0                    0.354270  ...                           -0.999669   
1                    0.503466  ...                           -0.999818   
2                    0.132061  ...                           -0.999566   
3                   -0.711894  ...                           -0.940882   
4                   -0.305964  ...                           -0.983249   
...                       ...  ...                                 ...   
5876                 0.419680  ...                           -0.999479   
5877                -0.260559  ...                           -0.956513   
5878                 0.155540  ...                           -0.999504   
5879                -0.229386  ...                           -0.959061   
5880                 0.505829  ...                           -0.999014   

      fBodyAccJerk-bandsEnerg

## 3. 단계별 모델링

In [126]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier()
model1.fit(x_train, y_train.drop('Activity_dynamic', axis = 1))
y1_pred = model1.predict(x_train)
x_train_a = x_train.iloc[y1_pred == 0]
x_train_b = x_train.iloc[y1_pred == 1]

<ipython-input-126-97817d10191f>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(x_train, y_train.drop('Activity_dynamic', axis = 1))


In [66]:
x_train[:10].index, x_train_a[:10].index, x_train_b[:10].index, y1_pred[:10]

(Int64Index([1313, 5747, 5262, 1949, 1780, 3296, 2035, 5072, 455, 5715], dtype='int64'),
 Int64Index([3296, 2035, 5715, 2418, 5455, 4006, 1613, 2099, 750, 688], dtype='int64'),
 Int64Index([1313, 5747, 5262, 1949, 1780, 5072, 455, 3254, 1343, 2145], dtype='int64'),
 array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0]))

In [127]:
model2 = RandomForestClassifier()
model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])

<ipython-input-127-2ec187c61a67>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])


RandomForestClassifier()

In [128]:
model3 = RandomForestClassifier()
model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])

<ipython-input-128-751b08850619>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])


RandomForestClassifier()

In [129]:
def double_model(x_train, y_train, data):
    # 1차 분류
    model1 = RandomForestClassifier()
    model1.fit(x_train, y_train.drop('Activity_dynamic', axis=1))
    # 분류 예측 결과
    y1_pred = model1.predict(x_train)
    # 0이면 여기에
    x_train_a = x_train.iloc[y1_pred == 0]
    # 1이면 여기에
    x_train_b = x_train.iloc[y1_pred == 1]
    # 0 -> 0, 1, 2 분류
    model2 = RandomForestClassifier()
    model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])
    # 1 -> 3, 4, 5 분류
    model3 = RandomForestClassifier()
    model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])

    temp = model1.predict(data)
    # 원본 순서를 저장
    idx = data.index
    # 데이터 분리
    data_a = data.iloc[temp == 0]
    data_b = data.iloc[temp == 1]
    ans_a = pd.DataFrame({'answer':model2.predict(data_a)}, index = data_a.index)
    ans_b = pd.DataFrame({'answer':model3.predict(data_b)}, index = data_b.index)
    # 결과 합치기
    ans = pd.concat([ans_a, ans_b])
    # 들어온 데이터 순서대로 재정렬해서 반환
    return ans.loc[idx]

In [70]:
y_test

Activity  Activity_dynamic
5574         1                 0
2078         0                 4
1579         0                 3
4585         1                 5
5384         0                 3
...        ...               ...
3457         0                 4
351          0                 4
4997         0                 3
2387         0                 4
2762         1                 5

[1177 rows x 2 columns]

In [71]:
score_model(data, 2023)

<ipython-input-69-5c3457c811e0>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(x_train, y_train.drop('Activity_dynamic', axis=1))
<ipython-input-69-5c3457c811e0>:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])
<ipython-input-69-5c3457c811e0>:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])


              precision    recall  f1-score   support

           0       0.74      0.80      0.77       180
           1       0.80      0.75      0.77       175
           2       0.81      0.78      0.79       165
           3       0.60      0.83      0.70       230
           4       0.56      0.80      0.66       218
           5       0.78      0.12      0.21       209

    accuracy                           0.67      1177
   macro avg       0.71      0.68      0.65      1177
weighted avg       0.71      0.67      0.64      1177

LAYING, SITTING, STANDING, WALKING, WALKING_DOWNSTAIRS, WALKING_UPSTAIRS, 
[[144  17  19   0   0   0]
 [ 31 132  12   0   0   0]
 [ 20  16 129   0   0   0]
 [  0   1   0 190  34   5]
 [  0   0   0  42 174   2]
 [  0   0   0  84 100  25]]


In [72]:
RFmodel = RandomForestClassifier()
RFmodel.fit(x_train, y_train.drop('Activity', axis = 1))
RFmodel.score(x_test, y_test.drop('Activity', axis = 1))
y_pred = RFmodel. predict(x_test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))

<ipython-input-72-bb58bbaf0805>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFmodel.fit(x_train, y_train.drop('Activity', axis = 1))


              precision    recall  f1-score   support

           0       0.70      0.78      0.74       180
           1       0.78      0.74      0.76       175
           2       0.79      0.73      0.76       165
           3       0.67      0.77      0.72       230
           4       0.66      0.71      0.68       218
           5       0.59      0.45      0.51       209

    accuracy                           0.69      1177
   macro avg       0.70      0.70      0.69      1177
weighted avg       0.69      0.69      0.69      1177

[[140  19  21   0   0   0]
 [ 34 129  12   0   0   0]
 [ 26  18 121   0   0   0]
 [  0   0   0 178  22  30]
 [  0   0   0  29 154  35]
 [  0   0   0  58  57  94]]


In [73]:
# test dataset 학습
y_pred = RFmodel. predict(test)


In [55]:
y_pred

array([2, 2, 3, ..., 4, 0, 4])

In [74]:
# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
result_df = pd.DataFrame({'Activity': y_pred})

# ID 열 추가
result_df.insert(0, 'ID', test.index)

# 결과 확인
print(result_df.head())

   ID  Activity
0   0         5
1   1         4
2   2         0
3   3         5
4   4         3


In [75]:
result_df.to_csv(path + 'RF모델.csv', index=False)

### DBN 모델

In [79]:
x_test

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
5574          -0.118268                0.193008               -0.239023   
2078          -0.117428               -0.011270                0.131772   
1579          -0.100084               -0.102401                0.264757   
4585          -0.105258               -0.190555                0.256784   
5384          -0.124193               -0.000518               -0.033752   
...                 ...                     ...                     ...   
3457          -0.109975               -0.113580                0.478743   
351           -0.127987               -0.133399                0.215161   
4997          -0.108790               -0.046675                0.116311   
2387          -0.122546                0.050501                0.084244   
2762          -0.103206               -0.373093                0.225880   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
5574              -0.001576               0.446362   
2078               0.073828               0.007050   
1579               0.054158               0.001237   
4585               0.077466               0.015030   
5384               0.089808               0.034478   
...                     ...                    ...   
3457               0.080066               0.020383   
351                0.074153              -0.003533   
4997               0.081887               0.011555   
2387               0.069744               0.115594   
2762               0.076045               0.015320   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
5574                    0.219803                   -0.273264   
2078                    0.342710                    0.048010   
1579                   -0.100180                    0.365871   
4585                    0.086831                    0.307635   
5384                    0.017338                    0.108457   
...                          ...                         ...   
3457                    0.277802                    0.466308   
351                     0.283156                    0.292998   
4997                    0.106443                   -0.009542   
2387                    0.445466                    0.182409   
2762                   -0.004786                    0.251513   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
5574                    0.385142                   -0.190643   
2078                   -0.059330                    0.149320   
1579                    0.460315                    0.173074   
4585                    0.521321                    0.253901   
5384                    0.488424                    0.159830   
...                          ...                         ...   
3457                    0.441577                    0.267915   
351                     0.351556                    0.349739   
4997                    0.250371                    0.149415   
2387                    0.562940                   -0.060225   
2762                    0.285838                    0.182473   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
5574                 0.032881  ...                           -0.980203   
2078                 0.185672  ...                           -0.999812   
1579                 0.145416  ...                           -0.999610   
4585                 0.328305  ...                           -0.999501   
5384                 0.044201  ...                           -0.998626   
...                       ...  ...                                 ...   
3457                 0.278971  ...                           -0.999455   
351                  0.324026  ...                           -0.999620   
4997                 0.056729  ...                           -0.999445   
2387                 0.236994  ...                           -0.997140   
2762                -0.101047  ...                           -0.999681   

      fBodyAccJerk-bandsEnerg

In [80]:
test

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
0             -0.116683                0.059275                0.005050   
1             -0.118412               -0.219041               -0.255267   
2             -0.087303                0.552368               -0.025095   
3             -0.108381               -0.097072                0.198134   
4             -0.078856                0.202431               -0.546042   
...                 ...                     ...                     ...   
1466          -0.106398               -0.081939                0.185382   
1467          -0.109078               -0.191660                0.252811   
1468          -0.121377                0.190174               -0.004620   
1469          -0.116644                0.103635                0.263890   
1470          -0.083858                0.183636               -0.218482   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
0                  0.074204               0.005466   
1                  0.076562               0.000427   
2                  0.069317               0.251780   
3                  0.078063              -0.003247   
4                  0.066171               0.089363   
...                     ...                    ...   
1466               0.071741               0.009478   
1467               0.075298               0.007827   
1468               0.282992              -0.166026   
1469               0.089082              -0.006599   
1470              -0.030629              -0.084982   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
0                       0.229130                    0.064325   
1                       0.027814                   -0.278551   
2                       0.586216                   -0.079610   
3                       0.235713                    0.110652   
4                       0.205810                   -0.576410   
...                          ...                         ...   
1466                    0.019718                    0.246692   
1467                    0.218177                    0.220255   
1468                    0.282091                   -0.016718   
1469                    0.335221                    0.083270   
1470                    0.041531                   -0.309509   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
0                       0.208520                    0.128505   
1                      -0.008195                    0.044317   
2                       0.096668                   -0.219583   
3                      -0.056465                    0.164869   
4                      -0.394336                    0.111303   
...                          ...                         ...   
1466                    0.370205                    0.002332   
1467                    0.243859                    0.323898   
1468                    0.446784                   -0.189417   
1469                    0.160313                    0.504003   
1470                    0.180688                   -0.209794   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
0                    0.178639  ...                           -0.999635   
1                   -0.057602  ...                           -0.999677   
2                   -0.469174  ...                           -0.907521   
3                    0.319642  ...                           -0.999328   
4                    0.194097  ...                           -0.999203   
...                       ...  ...                                 ...   
1466                 0.232695  ...                           -0.999736   
1467                 0.106566  ...                           -0.999414   
1468                -0.223721  ...                           -0.703363   
1469                -0.073582  ...                           -0.999296   
1470                -0.009915  ...                           -0.895324   

      fBodyAccJerk-bandsEnerg

In [86]:
y_test

Activity  Activity_dynamic
1313         1                 0
5747         1                 5
5262         1                 5
1949         1                 2
1780         1                 5
...        ...               ...
884          1                 5
5852         1                 1
2743         1                 5
5657         0                 3
4951         0                 4

[4704 rows x 2 columns]

In [82]:
num_classes = 6

In [92]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import categorical_crossentropy

# Set random seed for reproducibility
tf.random.set_seed(2023)

# Build the model
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=x_train.shape[1]))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(6, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001),loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(x_train, y_train.drop('Activity', axis = 1), epochs=100, batch_size=32, validation_data=(x_test, y_test.drop('Activity', axis = 1)), verbose=0)

# Test the model
loss, accuracy = model.evaluate(x_test, y_test.drop('Activity', axis = 1))
print("Accuracy:", accuracy)


37/37 [==============================] - 0s 2ms/step - loss: 0.6687 - accuracy: 0.7094
Accuracy: 0.7094307541847229


In [93]:
DBN_pred = model.predict(test)


46/46 [==============================] - 0s 1ms/step


In [94]:
DBN_pred

array([[3.05252282e-11, 1.83295256e-07, 1.17689976e-14, 1.66153774e-01,
        4.56565171e-01, 3.77280891e-01],
       [4.46531375e-13, 1.07017756e-10, 5.75281304e-20, 8.84142518e-03,
        7.91904867e-01, 1.99253619e-01],
       [9.99991655e-01, 4.48689843e-06, 3.84394616e-06, 4.52012472e-09,
        1.17132852e-13, 1.75129938e-10],
       ...,
       [6.50854636e-05, 1.40356451e-06, 9.99933481e-01, 2.89649194e-10,
        7.03044289e-10, 1.23628852e-09],
       [6.81691361e-08, 9.02547299e-07, 3.34874822e-10, 8.41925681e-01,
        2.33936943e-02, 1.34679675e-01],
       [6.82062702e-03, 6.87810883e-04, 9.92491543e-01, 3.53431867e-12,
        3.88651909e-16, 1.14638117e-13]], dtype=float32)

In [95]:
predicted_classes = DBN_pred.argmax(axis=1)


In [96]:
predicted_classes


array([4, 4, 0, ..., 2, 3, 2])

In [97]:
# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
DBN_result_df = pd.DataFrame({'Activity': predicted_classes})

# ID 열 추가
DBN_result_df.insert(0, 'ID', test.index)

# 결과 확인
print(DBN_result_df.head())

DBN_result_df.to_csv(path + 'DBN모델.csv', index=False)


   ID  Activity
0   0         4
1   1         4
2   2         0
3   3         5
4   4         4


### RBM

In [99]:
from sklearn.neural_network import BernoulliRBM
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# RBM 모델 생성
rbm = BernoulliRBM(n_components=300, learning_rate=0.01, n_iter=100, random_state=0, verbose=True)

# 로지스틱 회귀 모델 생성
logistic = LogisticRegression(C=6000, penalty='l2', tol=0.0001, solver='sag')

# 파이프라인 구축
dbn = Pipeline(steps=[('rbm', rbm), ('logistic', logistic)])

# DBN 모델 학습
dbn.fit(x_train, y_train.drop('Activity', axis = 1))

# DBN 모델 예측
dbn_y_pred = dbn.predict(test)


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 1, pseudo-likelihood = -34.94, time = 0.20s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 2, pseudo-likelihood = -67.53, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 3, pseudo-likelihood = -100.11, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 4, pseudo-likelihood = -133.11, time = 0.27s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 5, pseudo-likelihood = -165.66, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 6, pseudo-likelihood = -198.10, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 7, pseudo-likelihood = -230.83, time = 0.35s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 8, pseudo-likelihood = -264.08, time = 0.37s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 9, pseudo-likelihood = -296.31, time = 0.34s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 10, pseudo-likelihood = -328.78, time = 0.33s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 11, pseudo-likelihood = -361.50, time = 0.46s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 12, pseudo-likelihood = -394.65, time = 0.51s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 13, pseudo-likelihood = -427.03, time = 0.47s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 14, pseudo-likelihood = -459.53, time = 0.50s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 15, pseudo-likelihood = -492.32, time = 0.48s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 16, pseudo-likelihood = -525.09, time = 0.50s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 17, pseudo-likelihood = -557.55, time = 0.49s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 18, pseudo-likelihood = -590.10, time = 0.45s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 19, pseudo-likelihood = -622.82, time = 0.37s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 20, pseudo-likelihood = -655.49, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 21, pseudo-likelihood = -688.73, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 22, pseudo-likelihood = -720.92, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 23, pseudo-likelihood = -753.82, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 24, pseudo-likelihood = -786.19, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 25, pseudo-likelihood = -818.90, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 26, pseudo-likelihood = -851.42, time = 0.31s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 27, pseudo-likelihood = -884.40, time = 0.28s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 28, pseudo-likelihood = -916.86, time = 0.32s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 29, pseudo-likelihood = -949.67, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 30, pseudo-likelihood = -982.10, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 31, pseudo-likelihood = -1015.03, time = 0.28s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 32, pseudo-likelihood = -1047.55, time = 0.32s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 33, pseudo-likelihood = -1080.51, time = 0.40s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 34, pseudo-likelihood = -1113.14, time = 0.33s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 35, pseudo-likelihood = -1145.61, time = 0.38s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 36, pseudo-likelihood = -1178.46, time = 0.34s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 37, pseudo-likelihood = -1211.00, time = 0.55s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 38, pseudo-likelihood = -1243.83, time = 0.39s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 39, pseudo-likelihood = -1276.60, time = 0.35s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 40, pseudo-likelihood = -1309.14, time = 0.32s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 41, pseudo-likelihood = -1341.89, time = 0.45s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 42, pseudo-likelihood = -1374.46, time = 0.54s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 43, pseudo-likelihood = -1407.23, time = 0.35s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 44, pseudo-likelihood = -1439.70, time = 0.31s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 45, pseudo-likelihood = -1472.41, time = 0.34s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 46, pseudo-likelihood = -1505.39, time = 0.50s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 47, pseudo-likelihood = -1537.67, time = 0.43s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 48, pseudo-likelihood = -1570.50, time = 1.03s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 49, pseudo-likelihood = -1603.18, time = 1.13s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 50, pseudo-likelihood = -1635.57, time = 0.92s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 51, pseudo-likelihood = -1668.53, time = 0.83s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 52, pseudo-likelihood = -1700.99, time = 0.44s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 53, pseudo-likelihood = -1733.49, time = 0.28s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 54, pseudo-likelihood = -1766.55, time = 0.32s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 55, pseudo-likelihood = -1799.08, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 56, pseudo-likelihood = -1831.86, time = 0.40s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 57, pseudo-likelihood = -1864.48, time = 0.39s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 58, pseudo-likelihood = -1897.19, time = 0.40s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 59, pseudo-likelihood = -1929.49, time = 0.47s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 60, pseudo-likelihood = -1962.23, time = 0.33s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 61, pseudo-likelihood = -1994.87, time = 0.57s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 62, pseudo-likelihood = -2027.61, time = 0.48s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 63, pseudo-likelihood = -2060.30, time = 0.47s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 64, pseudo-likelihood = -2092.97, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 65, pseudo-likelihood = -2125.92, time = 0.31s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 66, pseudo-likelihood = -2158.47, time = 0.31s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 67, pseudo-likelihood = -2190.97, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 68, pseudo-likelihood = -2223.84, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 69, pseudo-likelihood = -2256.28, time = 0.31s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 70, pseudo-likelihood = -2289.12, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 71, pseudo-likelihood = -2322.10, time = 0.31s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 72, pseudo-likelihood = -2354.25, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 73, pseudo-likelihood = -2387.06, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 74, pseudo-likelihood = -2419.74, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 75, pseudo-likelihood = -2452.42, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 76, pseudo-likelihood = -2485.52, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 77, pseudo-likelihood = -2517.84, time = 0.28s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 78, pseudo-likelihood = -2550.43, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 79, pseudo-likelihood = -2583.20, time = 0.27s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 80, pseudo-likelihood = -2615.69, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 81, pseudo-likelihood = -2648.48, time = 0.32s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 82, pseudo-likelihood = -2681.22, time = 0.50s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 83, pseudo-likelihood = -2713.76, time = 0.49s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 84, pseudo-likelihood = -2746.41, time = 0.44s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 85, pseudo-likelihood = -2779.31, time = 0.49s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 86, pseudo-likelihood = -2811.57, time = 0.47s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 87, pseudo-likelihood = -2844.45, time = 0.49s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 88, pseudo-likelihood = -2877.01, time = 0.49s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 89, pseudo-likelihood = -2910.05, time = 0.49s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 90, pseudo-likelihood = -2942.74, time = 0.34s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 91, pseudo-likelihood = -2975.19, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 92, pseudo-likelihood = -3008.33, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 93, pseudo-likelihood = -3040.62, time = 0.31s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 94, pseudo-likelihood = -3073.66, time = 0.29s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 95, pseudo-likelihood = -3105.71, time = 0.28s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 96, pseudo-likelihood = -3138.45, time = 0.30s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 97, pseudo-likelihood = -3171.17, time = 0.31s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 98, pseudo-likelihood = -3204.23, time = 0.32s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 99, pseudo-likelihood = -3236.56, time = 0.40s


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(


[BernoulliRBM] Iteration 100, pseudo-likelihood = -3269.55, time = 0.51s


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [100]:
# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
dbn_result_df = pd.DataFrame({'Activity': dbn_y_pred})

# ID 열 추가
dbn_result_df.insert(0, 'ID', test.index)

# 결과 확인
print(dbn_result_df.head())

dbn_result_df.to_csv(path + 'dbn모델.csv', index=False)


   ID  Activity
0   0         3
1   1         3
2   2         3
3   3         3
4   4         3


### XGBoost

In [101]:
import xgboost as xgb

XGBmodel = xgb.XGBClassifier()
XGBmodel.fit(x_train, y_train.drop('Activity', axis=1))
XGBmodel.score(x_test, y_test.drop('Activity', axis=1))
y_pred = XGBmodel.predict(x_test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


              precision    recall  f1-score   support

           0       0.84      0.86      0.85       180
           1       0.84      0.85      0.84       175
           2       0.86      0.84      0.85       165
           3       0.76      0.80      0.78       230
           4       0.71      0.74      0.73       218
           5       0.64      0.57      0.60       209

    accuracy                           0.77      1177
   macro avg       0.78      0.78      0.78      1177
weighted avg       0.77      0.77      0.77      1177

[[155  13  12   0   0   0]
 [ 18 148   9   0   0   0]
 [ 11  16 138   0   0   0]
 [  0   0   1 184  16  29]
 [  0   0   0  17 162  39]
 [  0   0   0  41  49 119]]


In [105]:
# test dataset 학습
y_pred = XGBmodel. predict(test)

# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
XGBresult_df = pd.DataFrame({'Activity': y_pred})

# ID 열 추가
XGBresult_df.insert(0, 'ID', test.index)

# 결과 확인
print(XGBresult_df.head())

XGBresult_df.to_csv(path + 'XGB 모델2.csv', index=False)

   ID  Activity
0   0         5
1   1         4
2   2         0
3   3         5
4   4         4


### XGB 튜닝

In [143]:
from sklearn.model_selection import RandomizedSearchCV
import xgboost as xgb
import numpy as np

XGBmodel = xgb.XGBClassifier()

# 탐색할 하이퍼파라미터들을 설정합니다.
param_distributions = {
    'n_estimators': [50, 100, 150],
    'max_depth': range(3, 6),
    'learning_rate': np.logspace(-3, -1, num=10)
}

# 랜덤 서치를 설정합니다.
random_search = RandomizedSearchCV(
    XGBmodel, 
    param_distributions, 
    cv=5, 
    n_iter=10, 
    n_jobs=-1
)

# 랜덤 서치를 실행합니다.
random_search.fit(x_train, y_train.drop('Activity', axis=1))

print("Best Parameters: ", random_search.best_params_)
print("Best Score: ", random_search.best_score_)

# 학습된 모델을 사용하여 예측합니다.
y_pred = random_search.predict(x_test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


KeyboardInterrupt: ignored

## Voting

In [139]:
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import VotingClassifier

# XGBoost 모델
XGBmodel = xgb.XGBClassifier(n_estimators=150, max_depth=5, learning_rate=0.1)

# LightGBM 모델
lgbm = lgb.LGBMClassifier(n_estimators=100, max_depth=4, learning_rate=0.1)

# 앙상블 모델
voting_clf = VotingClassifier(estimators=[('xgb', XGBmodel), ('lgbm', lgbm)], voting='soft')

# 학습
voting_clf.fit(x_train, y_train.drop('Activity', axis=1))

# 예측
y_pred = voting_clf.predict(x_test)

# 결과 출력
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


              precision    recall  f1-score   support

           0       0.81      0.84      0.83       180
           1       0.81      0.82      0.82       175
           2       0.87      0.83      0.85       165
           3       0.75      0.79      0.77       230
           4       0.70      0.75      0.72       218
           5       0.65      0.56      0.60       209

    accuracy                           0.76      1177
   macro avg       0.76      0.76      0.76      1177
weighted avg       0.76      0.76      0.76      1177

[[151  17  12   0   0   0]
 [ 24 144   7   0   0   0]
 [ 11  17 137   0   0   0]
 [  0   0   1 182  20  27]
 [  0   0   0  19 163  36]
 [  0   0   0  42  51 116]]


In [141]:
import re
test = test.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

In [142]:
# test dataset 학습
y_pred = voting_clf. predict(test)

# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
VTresult_df = pd.DataFrame({'Activity': y_pred})

# ID 열 추가
VTresult_df.insert(0, 'ID', test.index)

# 결과 확인
print(VTresult_df.head())

VTresult_df.to_csv(path + 'VT 모델.csv', index=False)

   ID  Activity
0   0         5
1   1         4
2   2         0
3   3         5
4   4         3


## 전처리 수정

In [161]:
def select_top_features(model, x_train, x_test, num_features=30):
    """
    Select top features based on feature importance of model
    """
    # 모델 학습
    model.fit(x_train, y_train)

    # 변수 중요도 계산
    feature_importances = model.feature_importances_

    # 상위 num_features개의 변수 추출
    top_features = x_train.columns[np.argsort(feature_importances)[::-1][:num_features]]

    # 새로운 데이터프레임 생성
    x_train_new = x_train[top_features]
    x_test_new = x_test[top_features]

    return x_train_new, x_test_new


In [165]:
# RandomForestClassifier 모델을 사용하여 x_train과 x_test에서 변수 중요도가 가장 높은 상위 30개의 변수만 추출
x_train_new, test_new = select_top_features(RandomForestClassifier(), x_train, test, num_features=30)


In [169]:
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import VotingClassifier

# XGBoost 모델
XGBmodel = xgb.XGBClassifier(n_estimators=150, max_depth=5, learning_rate=0.1)

# LightGBM 모델
lgbm = lgb.LGBMClassifier(n_estimators=100, max_depth=4, learning_rate=0.1)

# 앙상블 모델
voting_clf = VotingClassifier(estimators=[('xgb', XGBmodel), ('lgbm', lgbm)], voting='soft')

# 학습
voting_clf.fit(x_train_new, y_train.drop('Activity', axis=1))

# 예측
y_pred = voting_clf.predict(test_new)

# # 결과 출력
# print(classification_report(y_test['Activity_dynamic'], y_pred))
# print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [170]:
# test dataset 학습
y_pred = voting_clf. predict(test_new)

# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
VT_process_result_df = pd.DataFrame({'Activity': y_pred})

# ID 열 추가
VT_process_result_df.insert(0, 'ID', test.index)

# 결과 확인
print(VT_process_result_df.head())

VT_process_result_df.to_csv(path + 'VT_process_ 모델.csv', index=False)

   ID  Activity
0   0         5
1   1         4
2   2         0
3   3         5
4   4         4


## Voting 튜닝

## 그리드서치

In [171]:
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import RandomizedSearchCV

# XGBoost 모델
XGBmodel = xgb.XGBClassifier()

# LightGBM 모델
lgbm = lgb.LGBMClassifier()

# 하이퍼파라미터 탐색 범위
xgb_param_grid = {
    'n_estimators': [100, 150, 200],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.1, 0.01, 0.001],
    'gamma': [0, 0.1, 0.2],
    'subsample': [0.5, 0.7, 1],
    'colsample_bytree': [0.5, 0.7, 1],
}

lgbm_param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.1, 0.01, 0.001],
    'min_child_samples': [10, 20, 30],
    'subsample': [0.5, 0.7, 1],
    'colsample_bytree': [0.5, 0.7, 1],
}

# 랜덤서치
xgb_random_search = RandomizedSearchCV(XGBmodel, param_distributions=xgb_param_grid, n_iter=100, cv=5)
lgbm_random_search = RandomizedSearchCV(lgbm, param_distributions=lgbm_param_grid, n_iter=100, cv=5)

# XGBoost 모델 학습
xgb_random_search.fit(x_train, y_train.drop('Activity', axis=1))
XGBmodel.set_params(**xgb_random_search.best_params_)

# LightGBM 모델 학습
lgbm_random_search.fit(x_train, y_train.drop('Activity', axis=1))
lgbm.set_params(**lgbm_random_search.best_params_)

# 앙상블 모델
voting_clf = VotingClassifier(estimators=[('xgb', XGBmodel), ('lgbm', lgbm)], voting='soft')

# 학습
voting_clf.fit(x_train, y_train.drop('Activity', axis=1))

# 예측
y_pred = voting_clf.predict(x_test)

# 결과 출력
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


KeyboardInterrupt: ignored

## 랜덤서치

In [144]:
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform

# XGBoost 모델
XGBmodel = xgb.XGBClassifier()

# LightGBM 모델
lgbm = lgb.LGBMClassifier()

# 앙상블 모델
voting_clf = VotingClassifier(estimators=[('xgb', XGBmodel), ('lgbm', lgbm)], voting='soft')

# 하이퍼파라미터 조합 설정
param_distribs = {
    'xgb__n_estimators': randint(50, 200),
    'xgb__max_depth': randint(3, 6),
    'xgb__learning_rate': uniform(0.001, 0.1),
    'lgbm__n_estimators': randint(50, 200),
    'lgbm__max_depth': randint(3, 6),
    'lgbm__learning_rate': uniform(0.001, 0.1),
}

# 랜덤서치 객체 생성
rnd_search = RandomizedSearchCV(voting_clf, param_distributions=param_distribs, n_iter=10, cv=5, scoring='accuracy', random_state=42)

# 랜덤서치 수행
rnd_search.fit(x_train, y_train.drop('Activity', axis=1))

# 최적의 하이퍼파라미터와 성능 출력
print("Best Parameters: ", rnd_search.best_params_)
print("Best Score: ", rnd_search.best_score_)

# 예측
y_pred = rnd_search.predict(x_test)

# 결과 출력
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shap

Best Parameters:  {'lgbm__learning_rate': 0.046049925196954306, 'lgbm__max_depth': 4, 'lgbm__n_estimators': 181, 'xgb__learning_rate': 0.09522017556848528, 'xgb__max_depth': 4, 'xgb__n_estimators': 58}
Best Score:  0.7138603115743777
              precision    recall  f1-score   support

           0       0.77      0.81      0.79       180
           1       0.78      0.78      0.78       175
           2       0.83      0.79      0.81       165
           3       0.72      0.80      0.76       230
           4       0.68      0.74      0.71       218
           5       0.65      0.50      0.56       209

    accuracy                           0.73      1177
   macro avg       0.74      0.74      0.74      1177
weighted avg       0.73      0.73      0.73      1177

[[145  18  17   0   0   0]
 [ 30 137   8   0   0   0]
 [ 13  21 131   0   0   0]
 [  0   0   1 185  21  23]
 [  0   0   0  24 161  33]
 [  0   0   0  49  56 104]]


In [145]:
# test dataset 학습
y_pred = rnd_search. predict(test)

# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
VTRSresult_df = pd.DataFrame({'Activity': y_pred})

# ID 열 추가
VTRSresult_df.insert(0, 'ID', test.index)

# 결과 확인
print(VTRSresult_df.head())

VTRSresult_df.to_csv(path + 'VTRS 모델.csv', index=False)

   ID  Activity
0   0         5
1   1         4
2   2         0
3   3         5
4   4         3


## Auto

In [203]:
!pip install auto-sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [244]:
!sudo apt-get install build-essential swig
!pip install auto-sklearn==0.11.1

Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.8ubuntu1.1).
Suggested packages:
  swig-doc swig-examples swig4.0-examples swig4.0-doc
The following NEW packages will be installed:
  swig swig4.0
0 upgraded, 2 newly installed, 0 to remove and 24 not upgraded.
Need to get 1,086 kB of archives.
After this operation, 5,413 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 swig4.0 amd64 4.0.1-5build1 [1,081 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 swig all 4.0.1-5build1 [5,528 B]
Fetched 1,086 kB in 1s (1,384 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 2.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
deb

In [248]:
pip install pycaret


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 481.8/481.8 kB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 55.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.0/150.0 kB 19.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 13.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.8/105.8 kB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 6.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
 

In [252]:
from pycaret.classification import *

# 모델 초기화 및 설정
clf = setup(data = data, target = 'Activity_dynamic', session_id = 123, 
            silent = True, fold_strategy = 'stratifiedkfold', n_jobs = -1)

# 모델 학습 및 비교
best_model = compare_models(fold = 5, sort = 'Accuracy', n_select = 1)

# 최적 모델 튜닝
tuned_model = tune_model(best_model)

# 모델 예측
predictions = predict_model(tuned_model, data = data)

# 분류 보고서 출력
print(classification_report(predictions['Activity_dynamic'], predictions['Label']))

# 오차 행렬 출력
print(confusion_matrix(predictions['Activity_dynamic'], predictions['Label']))


# # 3. Auto-sklearn을 이용한 모델 생성 및 학습
# import autosklearn.classification
# from autosklearn.metrics import accuracy

# automl = autosklearn.classification.AutoSklearnClassifier(time_left_for_this_task=180)
# automl.fit(x_train, y_train.drop('Activity', axis=1))

# # 결과 평가
# y_pred = automl.predict(x_test)

# # 결과 출력
# print(classification_report(y_test['Activity_dynamic'], y_pred))
# print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


ImportError: ignored

In [198]:
import sklearn
print(sklearn.__version__)


1.2.2


In [202]:
import autosklearn.classification
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics


ImportError: ignored

In [197]:
automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=3600,  # 최대 시간(초) 설정
    per_run_time_limit=300,  # 최대 시간(초) 설정
    n_jobs=-1,  # 사용할 CPU 코어 수 설정 (-1은 모든 가능한 코어 사용)
    metric=autosklearn.metrics.accuracy,  # 평가 지표 설정
    )

automl.fit(x_train,  y_train.drop('Activity', axis=1, dataset_name='digits')


NameError: ignored

In [ ]:
y_pred = automl.predict(test)
print("Accuracy score", sklearn.metrics.accuracy_score(y_test['Activity_dynamic'], y_pred))


### CatBoost

In [107]:
pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 MB 9.1 MB/s eta 0:00:00


In [108]:
from catboost import CatBoostClassifier

CBmodel = CatBoostClassifier()
CBmodel.fit(x_train, y_train.drop('Activity', axis=1), verbose=False)
CBmodel.score(x_test, y_test.drop('Activity', axis=1))
y_pred = CBmodel.predict(x_test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


              precision    recall  f1-score   support

           0       0.83      0.86      0.85       180
           1       0.84      0.83      0.84       175
           2       0.89      0.86      0.87       165
           3       0.76      0.83      0.79       230
           4       0.69      0.72      0.71       218
           5       0.65      0.56      0.60       209

    accuracy                           0.77      1177
   macro avg       0.78      0.78      0.78      1177
weighted avg       0.77      0.77      0.77      1177

[[155  14  11   0   0   0]
 [ 22 146   7   0   0   0]
 [  9  14 142   0   0   0]
 [  0   0   0 191  23  16]
 [  0   0   0  14 157  47]
 [  0   0   0  47  46 116]]


In [112]:
# test dataset 학습
y_pred = CBmodel.predict(test)

# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
CBresult_df = pd.DataFrame({'Activity': y_pred.flatten()})

# ID 열 추가
CBresult_df.insert(0, 'ID', test.index)

# 결과 확인
print(CBresult_df.head())

CBresult_df.to_csv(path + 'CB 모델.csv', index=False)


   ID  Activity
0   0         5
1   1         4
2   2         0
3   3         5
4   4         4


### CatBoost 튜닝

In [113]:
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostClassifier

CBmodel = CatBoostClassifier()

param_grid = {
    'learning_rate': [0.05, 0.1, 0.2],
    'depth': [4, 6, 8],
    'l2_leaf_reg': [1, 3, 5],
    'iterations': [500, 1000]
}

grid_search = GridSearchCV(
    estimator=CBmodel, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

grid_search.fit(x_train, y_train.drop('Activity', axis=1))

best_params = grid_search.best_params_
print(f"Best parameters: {best_params}")

CBmodel = CatBoostClassifier(**best_params)
CBmodel.fit(x_train, y_train.drop('Activity', axis=1), verbose=False)

CBmodel.score(x_test, y_test.drop('Activity', axis=1))
y_pred = CBmodel.predict(test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


Fitting 5 folds for each of 54 candidates, totalling 270 fits


KeyboardInterrupt: ignored

### LogisticRegression

In [114]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(x_train, y_train.drop('Activity', axis=1))
logreg.score(x_test, y_test.drop('Activity', axis=1))
y_pred = logreg.predict(x_test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.73      0.79      0.76       180
           1       0.75      0.75      0.75       175
           2       0.80      0.74      0.77       165
           3       0.64      0.78      0.70       230
           4       0.62      0.67      0.65       218
           5       0.46      0.31      0.37       209

    accuracy                           0.67      1177
   macro avg       0.67      0.67      0.67      1177
weighted avg       0.66      0.67      0.66      1177

[[142  22  16   0   0   0]
 [ 30 131  14   0   0   0]
 [ 21  22 122   0   0   0]
 [  1   0   0 179  16  34]
 [  1   0   0  29 147  41]
 [  0   0   0  72  73  64]]


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### DT

In [116]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 모델 학습
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train.drop('Activity', axis=1))

# 성능 평가
dt.score(x_test, y_test.drop('Activity', axis=1))
y_pred = dt.predict(x_test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


              precision    recall  f1-score   support

           0       0.59      0.59      0.59       180
           1       0.60      0.63      0.62       175
           2       0.62      0.59      0.61       165
           3       0.54      0.55      0.54       230
           4       0.46      0.48      0.47       218
           5       0.37      0.34      0.36       209

    accuracy                           0.52      1177
   macro avg       0.53      0.53      0.53      1177
weighted avg       0.52      0.52      0.52      1177

[[107  41  32   0   0   0]
 [ 36 110  27   1   0   1]
 [ 38  28  98   1   0   0]
 [  0   0   0 126  45  59]
 [  0   3   0  47 104  64]
 [  0   0   0  59  78  72]]
