### 캐글 제출용

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
!gdown https://drive.google.com/uc?id=1j4lPOBinj9hgHFrUIYw6-6I1ZYqjTe4W
!gdown https://drive.google.com/uc?id=1-3X_0Wj2GnvSDKg_4N1HjIl_vcW7hKDu

/bin/bash: gdown https://drive.google.com/uc?id=1j4lPOBinj9hgHFrUIYw6-6I1ZYqjTe4W: No such file or directory
/bin/bash: gdown https://drive.google.com/uc?id=1-3X_0Wj2GnvSDKg_4N1HjIl_vcW7hKDu: No such file or directory


In [6]:
from google.colab import drive

# 구글 드라이브 마운트
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
path = '/content/drive/MyDrive/KT aivleschool/KT_aivle_school_AI_track/15. MINI_PJ5/Kaggle/'

In [59]:
data = pd.read_csv(path + 'train_dataset.csv')
test = pd.read_csv(path + 'test_dataset.csv')

In [11]:
data.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyGyro-min()-Y  \
5876                 0.419680  ...          -0.997983   
5877                -0.260559  ...          -0.951267   
5878                 0.155540  ...          -0.998177   
5879                -0.229386  ...          -0.687973   
5880                 0.505829  ...          -0.906829   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
5876                        -0.999967                  -0.987428   
5877                        -0.982422                  -0.561358   
5878                        -0.999920                  -0.989684   
5879                        -0.940509                  -0.465531   
5880                        -0.997315                  -0.979258   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
5876                      -1.000000                -0.981119   
5877                       0.241367                -0.415217   
5878                      -1.000000                -0.991452   
5879                       0.323401                -0.504324   
5880                      -1.000000                -0.949917   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
5876                   -0.983765                         0.052914   
5877                   -0.845447                         0.325461   
5878                   -0.989032                         0.362439   
5879                   -0.867993                         0.031915   
5880                   -0.988100                         0.463038   

      angle(tBodyAccMean,gravity)          Activity  Activity_dynamic  
5876                    -0.034888           SITTING                 5  
5877                     0.721718  WALKING_UPSTAIRS                 1  
5878                     0.060173            LAYING                 3  
5879                     0.260880  WALKING_UPSTAIRS                 1  
5880                     0.107690           SITTING                 5  

[5 rows x 52 columns]

In [51]:
test.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
1466          -0.106398               -0.081939                0.185382   
1467          -0.109078               -0.191660                0.252811   
1468          -0.121377                0.190174               -0.004620   
1469          -0.116644                0.103635                0.263890   
1470          -0.083858                0.183636               -0.218482   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
1466               0.071741               0.009478   
1467               0.075298               0.007827   
1468               0.282992              -0.166026   
1469               0.089082              -0.006599   
1470              -0.030629              -0.084982   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
1466                    0.019718                    0.246692   
1467                    0.218177                    0.220255   
1468                    0.282091                   -0.016718   
1469                    0.335221                    0.083270   
1470                    0.041531                   -0.309509   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
1466                    0.370205                    0.002332   
1467                    0.243859                    0.323898   
1468                    0.446784                   -0.189417   
1469                    0.160313                    0.504003   
1470                    0.180688                   -0.209794   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
1466                 0.232695  ...                           -0.999736   
1467                 0.106566  ...                           -0.999414   
1468                -0.223721  ...                           -0.703363   
1469                -0.073582  ...                           -0.999296   
1470                -0.009915  ...                           -0.895324   

      fBodyAccJerk-bandsEnergy()-49,64.2  fBodyGyro-min()-Y  \
1466                           -0.999642          -0.993454   
1467                           -0.999498          -0.999391   
1468                           -0.260255          -0.793648   
1469                           -0.998998          -0.954967   
1470                           -0.884323          -0.799233   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
1466                        -0.999949                  -0.988987   
1467                        -0.999986                  -0.996189   
1468                        -0.771367                  -0.120213   
1469                        -0.999361                  -0.945335   
1470                        -0.927293                   0.076213   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
1466                      -1.000000                -0.993440   
1467                      -1.000000                -0.998003   
1468                       0.711324                -0.110976   
1469                      -0.798901                -0.946530   
1470                       0.710326                -0.361945   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
1466                   -0.995521                         0.166124   
1467                   -0.994214                         0.425059   
1468                   -0.553784                         0.187655   
1469                   -0.954411                        -0.200412   
1470                   -0.813583                         0.032252   

      angle(tBodyAccMean,gravity)  
1466                    -0.054788  
1467                     0.076333  
1468                     0.330378  
1469                    -0.048474  
1470                     0.374865  

[5 rows x 50 columns]

## 데이터 전처리

In [60]:
def target_morphs(data, target = None, target_dynamic = None):
    df = data.copy()
    # target이 지정되지 않았으면 가장 마지막 열로 지정
    if target is None:
        target = data.columns[-1]
    # targets가 존재하지만 리스트가 아니라면 리스트로 변경
    if target_dynamic is not None:
        if not isinstance(target_dynamic, list):
            target_dynamic = [target_dynamic]
        # target이 targets에 포함되는지 여부를 target에 저장
        df[target] = df[target].apply(lambda x: 0 if x in target_dynamic else 1)
    return df

In [30]:
data.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyGyro-min()-Y  \
5876                 0.419680  ...          -0.997983   
5877                -0.260559  ...          -0.951267   
5878                 0.155540  ...          -0.998177   
5879                -0.229386  ...          -0.687973   
5880                 0.505829  ...          -0.906829   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
5876                        -0.999967                  -0.987428   
5877                        -0.982422                  -0.561358   
5878                        -0.999920                  -0.989684   
5879                        -0.940509                  -0.465531   
5880                        -0.997315                  -0.979258   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
5876                      -1.000000                -0.981119   
5877                       0.241367                -0.415217   
5878                      -1.000000                -0.991452   
5879                       0.323401                -0.504324   
5880                      -1.000000                -0.949917   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
5876                   -0.983765                         0.052914   
5877                   -0.845447                         0.325461   
5878                   -0.989032                         0.362439   
5879                   -0.867993                         0.031915   
5880                   -0.988100                         0.463038   

      angle(tBodyAccMean,gravity)          Activity  Activity_dynamic  
5876                    -0.034888           SITTING                 5  
5877                     0.721718  WALKING_UPSTAIRS                 1  
5878                     0.060173            LAYING                 3  
5879                     0.260880  WALKING_UPSTAIRS                 1  
5880                     0.107690           SITTING                 5  

[5 rows x 52 columns]

In [61]:
y = data[['Activity', 'Activity_dynamic']]
y

Activity  Activity_dynamic
0               STANDING                 4
1                 LAYING                 3
2               STANDING                 4
3                WALKING                 0
4     WALKING_DOWNSTAIRS                 2
...                  ...               ...
5876             SITTING                 5
5877    WALKING_UPSTAIRS                 1
5878              LAYING                 3
5879    WALKING_UPSTAIRS                 1
5880             SITTING                 5

[5881 rows x 2 columns]

In [62]:
target_morphs(data, 'Activity', ['STANDING', 'LAYING', 'SITTING'])

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
0             -0.103362               -0.094784               -0.109208   
1             -0.098163               -0.052478                0.464764   
2             -0.108717               -0.226718                0.301165   
3             -0.150354                0.549363               -0.384117   
4              0.091229               -0.091537               -0.610793   
...                 ...                     ...                     ...   
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
0                  0.068584              -0.014314   
1                  0.075947               0.004456   
2                  0.079530               0.014504   
3                 -0.309509              -0.201293   
4                  0.584212              -0.266815   
...                     ...                    ...   
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
0                       0.198600                   -0.073666   
1                       0.130310                    0.401913   
2                       0.111340                    0.263556   
3                       0.411714                   -0.372620   
4                      -0.248696                   -0.628852   
...                          ...                         ...   
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
0                       0.113098                   -0.058315   
1                       0.512569                    0.011987   
2                       0.562730                    0.314589   
3                       0.288349                   -0.259441   
4                       0.095282                   -0.240501   
...                          ...                         ...   
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyGyro-min()-Y  \
0                    0.354270  ...          -0.996607   
1                    0.503466  ...          -0.992681   
2                    0.132061  ...          -0.999971   
3                   -0.711894  ...          -0.876509   
4                   -0.305964  ...          -0.960097   
...                       ...  ...                ...   
5876                 0.419680  ...          -0.997983   
5877                -0.260559  ...          -0.951267   
5878                 0.155540  ...          -0.998177   
5879                -0.229386  ...          -0.687973   
5880                 0.505829  ...          -0.906829   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
0                           -0.999969                  -0.985141   
1                           -0.999941                  -0.988982   
2                           -

In [63]:
from sklearn.metrics import classification_report, confusion_matrix

def score_model(data, random_state = None):
    X, y, lb = data_processing(data)
    x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = random_state)
    print('='*150)
    y_pred = double_model(x_train, y_train, x_test)
    print(classification_report(y_test['Activity_dynamic'], y_pred))
    print('='*150)
    # 썼던 라벨(lb)가 주어진다면
    if lb is not None:
        # LabelEncoder가 숫자형 범주로 바꾸는데 사용한 class들을 가져오고
        values = lb.classes_
        # 그걸 다시 LabelEncoder를 이용해 숫자로 바꿔서
        keys = lb.transform(lb.classes_)
        # 재결합해서 번역 Dict 생성
        dictionary = dict(zip(keys, values))
        for _ in range(len(dictionary)):
            # 그래서 Confusion Matrix를 보기 쉽게 출력
            print(dictionary[_], end=', ')
    print()
    print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


In [64]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

def data_processing(data, target = 'Activity'):
    # target_dynamic 리스트에 들어있는 Activity는 0, 없으면 1
    df = target_morphs(data, target = target, target_dynamic = ['STANDING', 'LAYING', ' SITTING'])
    # Unused
    # ynum = len(lb.classes_)
    # 위의 is dynamic이 아닌 실제 값. morphs는 Activity를 덮어씌우게 만들어서 이렇게 따로 추가해 줘야 함.
    real_y = data['Activity_dynamic'].copy()
    # Activity_dynamic 에 저장
    df[f'{target}_dynamic'] = real_y
    target = [target, f'{target}_dynamic']
    X = df.drop(target, axis = 1)
    y = df[target]
    # lb를 반환하는 이유는 score_model에서
    return X, y, lb
X, y, lb = data_processing(data)
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 2023)

In [42]:
X

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
0             -0.103362               -0.094784               -0.109208   
1             -0.098163               -0.052478                0.464764   
2             -0.108717               -0.226718                0.301165   
3             -0.150354                0.549363               -0.384117   
4              0.091229               -0.091537               -0.610793   
...                 ...                     ...                     ...   
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
0                  0.068584              -0.014314   
1                  0.075947               0.004456   
2                  0.079530               0.014504   
3                 -0.309509              -0.201293   
4                  0.584212              -0.266815   
...                     ...                    ...   
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
0                       0.198600                   -0.073666   
1                       0.130310                    0.401913   
2                       0.111340                    0.263556   
3                       0.411714                   -0.372620   
4                      -0.248696                   -0.628852   
...                          ...                         ...   
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
0                       0.113098                   -0.058315   
1                       0.512569                    0.011987   
2                       0.562730                    0.314589   
3                       0.288349                   -0.259441   
4                       0.095282                   -0.240501   
...                          ...                         ...   
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
0                    0.354270  ...                           -0.999669   
1                    0.503466  ...                           -0.999818   
2                    0.132061  ...                           -0.999566   
3                   -0.711894  ...                           -0.940882   
4                   -0.305964  ...                           -0.983249   
...                       ...  ...                                 ...   
5876                 0.419680  ...                           -0.999479   
5877                -0.260559  ...                           -0.956513   
5878                 0.155540  ...                           -0.999504   
5879                -0.229386  ...                           -0.959061   
5880                 0.505829  ...                           -0.999014   

      fBodyAccJerk-bandsEnerg

## 3. 단계별 모델링

In [65]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier()
model1.fit(x_train, y_train.drop('Activity_dynamic', axis = 1))
y1_pred = model1.predict(x_train)
x_train_a = x_train.iloc[y1_pred == 0]
x_train_b = x_train.iloc[y1_pred == 1]

<ipython-input-65-97817d10191f>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(x_train, y_train.drop('Activity_dynamic', axis = 1))


In [66]:
x_train[:10].index, x_train_a[:10].index, x_train_b[:10].index, y1_pred[:10]

(Int64Index([1313, 5747, 5262, 1949, 1780, 3296, 2035, 5072, 455, 5715], dtype='int64'),
 Int64Index([3296, 2035, 5715, 2418, 5455, 4006, 1613, 2099, 750, 688], dtype='int64'),
 Int64Index([1313, 5747, 5262, 1949, 1780, 5072, 455, 3254, 1343, 2145], dtype='int64'),
 array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0]))

In [67]:
model2 = RandomForestClassifier()
model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])

<ipython-input-67-2ec187c61a67>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])


RandomForestClassifier()

In [68]:
model3 = RandomForestClassifier()
model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])

<ipython-input-68-751b08850619>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])


RandomForestClassifier()

In [69]:
def double_model(x_train, y_train, data):
    # 1차 분류
    model1 = RandomForestClassifier()
    model1.fit(x_train, y_train.drop('Activity_dynamic', axis=1))
    # 분류 예측 결과
    y1_pred = model1.predict(x_train)
    # 0이면 여기에
    x_train_a = x_train.iloc[y1_pred == 0]
    # 1이면 여기에
    x_train_b = x_train.iloc[y1_pred == 1]
    # 0 -> 0, 1, 2 분류
    model2 = RandomForestClassifier()
    model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])
    # 1 -> 3, 4, 5 분류
    model3 = RandomForestClassifier()
    model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])

    temp = model1.predict(data)
    # 원본 순서를 저장
    idx = data.index
    # 데이터 분리
    data_a = data.iloc[temp == 0]
    data_b = data.iloc[temp == 1]
    ans_a = pd.DataFrame({'answer':model2.predict(data_a)}, index = data_a.index)
    ans_b = pd.DataFrame({'answer':model3.predict(data_b)}, index = data_b.index)
    # 결과 합치기
    ans = pd.concat([ans_a, ans_b])
    # 들어온 데이터 순서대로 재정렬해서 반환
    return ans.loc[idx]

In [70]:
y_test

Activity  Activity_dynamic
5574         1                 0
2078         0                 4
1579         0                 3
4585         1                 5
5384         0                 3
...        ...               ...
3457         0                 4
351          0                 4
4997         0                 3
2387         0                 4
2762         1                 5

[1177 rows x 2 columns]

In [71]:
score_model(data, 2023)

<ipython-input-69-5c3457c811e0>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(x_train, y_train.drop('Activity_dynamic', axis=1))
<ipython-input-69-5c3457c811e0>:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])
<ipython-input-69-5c3457c811e0>:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])


              precision    recall  f1-score   support

           0       0.74      0.80      0.77       180
           1       0.80      0.75      0.77       175
           2       0.81      0.78      0.79       165
           3       0.60      0.83      0.70       230
           4       0.56      0.80      0.66       218
           5       0.78      0.12      0.21       209

    accuracy                           0.67      1177
   macro avg       0.71      0.68      0.65      1177
weighted avg       0.71      0.67      0.64      1177

LAYING, SITTING, STANDING, WALKING, WALKING_DOWNSTAIRS, WALKING_UPSTAIRS, 
[[144  17  19   0   0   0]
 [ 31 132  12   0   0   0]
 [ 20  16 129   0   0   0]
 [  0   1   0 190  34   5]
 [  0   0   0  42 174   2]
 [  0   0   0  84 100  25]]


In [72]:
RFmodel = RandomForestClassifier()
RFmodel.fit(x_train, y_train.drop('Activity', axis = 1))
RFmodel.score(x_test, y_test.drop('Activity', axis = 1))
y_pred = RFmodel. predict(x_test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))

<ipython-input-72-bb58bbaf0805>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFmodel.fit(x_train, y_train.drop('Activity', axis = 1))


              precision    recall  f1-score   support

           0       0.70      0.78      0.74       180
           1       0.78      0.74      0.76       175
           2       0.79      0.73      0.76       165
           3       0.67      0.77      0.72       230
           4       0.66      0.71      0.68       218
           5       0.59      0.45      0.51       209

    accuracy                           0.69      1177
   macro avg       0.70      0.70      0.69      1177
weighted avg       0.69      0.69      0.69      1177

[[140  19  21   0   0   0]
 [ 34 129  12   0   0   0]
 [ 26  18 121   0   0   0]
 [  0   0   0 178  22  30]
 [  0   0   0  29 154  35]
 [  0   0   0  58  57  94]]


In [73]:
# test dataset 학습
y_pred = RFmodel. predict(test)


In [55]:
y_pred

array([2, 2, 3, ..., 4, 0, 4])

In [74]:
# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
result_df = pd.DataFrame({'Activity': y_pred})

# ID 열 추가
result_df.insert(0, 'ID', test.index)

# 결과 확인
print(result_df.head())

   ID  Activity
0   0         5
1   1         4
2   2         0
3   3         5
4   4         3


In [75]:
result_df.to_csv(path + 'RF모델.csv', index=False)

### DBN 모델

In [79]:
x_test

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
5574          -0.118268                0.193008               -0.239023   
2078          -0.117428               -0.011270                0.131772   
1579          -0.100084               -0.102401                0.264757   
4585          -0.105258               -0.190555                0.256784   
5384          -0.124193               -0.000518               -0.033752   
...                 ...                     ...                     ...   
3457          -0.109975               -0.113580                0.478743   
351           -0.127987               -0.133399                0.215161   
4997          -0.108790               -0.046675                0.116311   
2387          -0.122546                0.050501                0.084244   
2762          -0.103206               -0.373093                0.225880   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
5574              -0.001576               0.446362   
2078               0.073828               0.007050   
1579               0.054158               0.001237   
4585               0.077466               0.015030   
5384               0.089808               0.034478   
...                     ...                    ...   
3457               0.080066               0.020383   
351                0.074153              -0.003533   
4997               0.081887               0.011555   
2387               0.069744               0.115594   
2762               0.076045               0.015320   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
5574                    0.219803                   -0.273264   
2078                    0.342710                    0.048010   
1579                   -0.100180                    0.365871   
4585                    0.086831                    0.307635   
5384                    0.017338                    0.108457   
...                          ...                         ...   
3457                    0.277802                    0.466308   
351                     0.283156                    0.292998   
4997                    0.106443                   -0.009542   
2387                    0.445466                    0.182409   
2762                   -0.004786                    0.251513   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
5574                    0.385142                   -0.190643   
2078                   -0.059330                    0.149320   
1579                    0.460315                    0.173074   
4585                    0.521321                    0.253901   
5384                    0.488424                    0.159830   
...                          ...                         ...   
3457                    0.441577                    0.267915   
351                     0.351556                    0.349739   
4997                    0.250371                    0.149415   
2387                    0.562940                   -0.060225   
2762                    0.285838                    0.182473   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
5574                 0.032881  ...                           -0.980203   
2078                 0.185672  ...                           -0.999812   
1579                 0.145416  ...                           -0.999610   
4585                 0.328305  ...                           -0.999501   
5384                 0.044201  ...                           -0.998626   
...                       ...  ...                                 ...   
3457                 0.278971  ...                           -0.999455   
351                  0.324026  ...                           -0.999620   
4997                 0.056729  ...                           -0.999445   
2387                 0.236994  ...                           -0.997140   
2762                -0.101047  ...                           -0.999681   

      fBodyAccJerk-bandsEnerg

In [80]:
test

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
0             -0.116683                0.059275                0.005050   
1             -0.118412               -0.219041               -0.255267   
2             -0.087303                0.552368               -0.025095   
3             -0.108381               -0.097072                0.198134   
4             -0.078856                0.202431               -0.546042   
...                 ...                     ...                     ...   
1466          -0.106398               -0.081939                0.185382   
1467          -0.109078               -0.191660                0.252811   
1468          -0.121377                0.190174               -0.004620   
1469          -0.116644                0.103635                0.263890   
1470          -0.083858                0.183636               -0.218482   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
0                  0.074204               0.005466   
1                  0.076562               0.000427   
2                  0.069317               0.251780   
3                  0.078063              -0.003247   
4                  0.066171               0.089363   
...                     ...                    ...   
1466               0.071741               0.009478   
1467               0.075298               0.007827   
1468               0.282992              -0.166026   
1469               0.089082              -0.006599   
1470              -0.030629              -0.084982   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
0                       0.229130                    0.064325   
1                       0.027814                   -0.278551   
2                       0.586216                   -0.079610   
3                       0.235713                    0.110652   
4                       0.205810                   -0.576410   
...                          ...                         ...   
1466                    0.019718                    0.246692   
1467                    0.218177                    0.220255   
1468                    0.282091                   -0.016718   
1469                    0.335221                    0.083270   
1470                    0.041531                   -0.309509   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
0                       0.208520                    0.128505   
1                      -0.008195                    0.044317   
2                       0.096668                   -0.219583   
3                      -0.056465                    0.164869   
4                      -0.394336                    0.111303   
...                          ...                         ...   
1466                    0.370205                    0.002332   
1467                    0.243859                    0.323898   
1468                    0.446784                   -0.189417   
1469                    0.160313                    0.504003   
1470                    0.180688                   -0.209794   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
0                    0.178639  ...                           -0.999635   
1                   -0.057602  ...                           -0.999677   
2                   -0.469174  ...                           -0.907521   
3                    0.319642  ...                           -0.999328   
4                    0.194097  ...                           -0.999203   
...                       ...  ...                                 ...   
1466                 0.232695  ...                           -0.999736   
1467                 0.106566  ...                           -0.999414   
1468                -0.223721  ...                           -0.703363   
1469                -0.073582  ...                           -0.999296   
1470                -0.009915  ...                           -0.895324   

      fBodyAccJerk-bandsEnerg

In [86]:
y_test

Activity  Activity_dynamic
1313         1                 0
5747         1                 5
5262         1                 5
1949         1                 2
1780         1                 5
...        ...               ...
884          1                 5
5852         1                 1
2743         1                 5
5657         0                 3
4951         0                 4

[4704 rows x 2 columns]

In [82]:
num_classes = 6

In [92]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import categorical_crossentropy

# Set random seed for reproducibility
tf.random.set_seed(2023)

# Build the model
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=x_train.shape[1]))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(6, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001),loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(x_train, y_train.drop('Activity', axis = 1), epochs=100, batch_size=32, validation_data=(x_test, y_test.drop('Activity', axis = 1)), verbose=0)

# Test the model
loss, accuracy = model.evaluate(x_test, y_test.drop('Activity', axis = 1))
print("Accuracy:", accuracy)


37/37 [==============================] - 0s 2ms/step - loss: 0.6687 - accuracy: 0.7094
Accuracy: 0.7094307541847229


In [93]:
DBN_pred = model.predict(test)


46/46 [==============================] - 0s 1ms/step


In [94]:
DBN_pred

array([[3.05252282e-11, 1.83295256e-07, 1.17689976e-14, 1.66153774e-01,
        4.56565171e-01, 3.77280891e-01],
       [4.46531375e-13, 1.07017756e-10, 5.75281304e-20, 8.84142518e-03,
        7.91904867e-01, 1.99253619e-01],
       [9.99991655e-01, 4.48689843e-06, 3.84394616e-06, 4.52012472e-09,
        1.17132852e-13, 1.75129938e-10],
       ...,
       [6.50854636e-05, 1.40356451e-06, 9.99933481e-01, 2.89649194e-10,
        7.03044289e-10, 1.23628852e-09],
       [6.81691361e-08, 9.02547299e-07, 3.34874822e-10, 8.41925681e-01,
        2.33936943e-02, 1.34679675e-01],
       [6.82062702e-03, 6.87810883e-04, 9.92491543e-01, 3.53431867e-12,
        3.88651909e-16, 1.14638117e-13]], dtype=float32)

In [95]:
predicted_classes = DBN_pred.argmax(axis=1)


In [96]:
predicted_classes


array([4, 4, 0, ..., 2, 3, 2])

In [97]:
# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
DBN_result_df = pd.DataFrame({'Activity': predicted_classes})

# ID 열 추가
DBN_result_df.insert(0, 'ID', test.index)

# 결과 확인
print(DBN_result_df.head())

DBN_result_df.to_csv(path + 'DBN모델.csv', index=False)


   ID  Activity
0   0         4
1   1         4
2   2         0
3   3         5
4   4         4
