### 캐글 제출용

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
!gdown https://drive.google.com/uc?id=1j4lPOBinj9hgHFrUIYw6-6I1ZYqjTe4W
!gdown https://drive.google.com/uc?id=1-3X_0Wj2GnvSDKg_4N1HjIl_vcW7hKDu

/bin/bash: gdown https://drive.google.com/uc?id=1j4lPOBinj9hgHFrUIYw6-6I1ZYqjTe4W: No such file or directory
/bin/bash: gdown https://drive.google.com/uc?id=1-3X_0Wj2GnvSDKg_4N1HjIl_vcW7hKDu: No such file or directory


In [6]:
from google.colab import drive

# 구글 드라이브 마운트
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
path = '/content/drive/MyDrive/KT aivleschool/KT_aivle_school_AI_track/15. MINI_PJ5/Kaggle/'

In [59]:
data = pd.read_csv(path + 'train_dataset.csv')
test = pd.read_csv(path + 'test_dataset.csv')

In [11]:
data.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyGyro-min()-Y  \
5876                 0.419680  ...          -0.997983   
5877                -0.260559  ...          -0.951267   
5878                 0.155540  ...          -0.998177   
5879                -0.229386  ...          -0.687973   
5880                 0.505829  ...          -0.906829   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
5876                        -0.999967                  -0.987428   
5877                        -0.982422                  -0.561358   
5878                        -0.999920                  -0.989684   
5879                        -0.940509                  -0.465531   
5880                        -0.997315                  -0.979258   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
5876                      -1.000000                -0.981119   
5877                       0.241367                -0.415217   
5878                      -1.000000                -0.991452   
5879                       0.323401                -0.504324   
5880                      -1.000000                -0.949917   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
5876                   -0.983765                         0.052914   
5877                   -0.845447                         0.325461   
5878                   -0.989032                         0.362439   
5879                   -0.867993                         0.031915   
5880                   -0.988100                         0.463038   

      angle(tBodyAccMean,gravity)          Activity  Activity_dynamic  
5876                    -0.034888           SITTING                 5  
5877                     0.721718  WALKING_UPSTAIRS                 1  
5878                     0.060173            LAYING                 3  
5879                     0.260880  WALKING_UPSTAIRS                 1  
5880                     0.107690           SITTING                 5  

[5 rows x 52 columns]

In [51]:
test.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
1466          -0.106398               -0.081939                0.185382   
1467          -0.109078               -0.191660                0.252811   
1468          -0.121377                0.190174               -0.004620   
1469          -0.116644                0.103635                0.263890   
1470          -0.083858                0.183636               -0.218482   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
1466               0.071741               0.009478   
1467               0.075298               0.007827   
1468               0.282992              -0.166026   
1469               0.089082              -0.006599   
1470              -0.030629              -0.084982   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
1466                    0.019718                    0.246692   
1467                    0.218177                    0.220255   
1468                    0.282091                   -0.016718   
1469                    0.335221                    0.083270   
1470                    0.041531                   -0.309509   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
1466                    0.370205                    0.002332   
1467                    0.243859                    0.323898   
1468                    0.446784                   -0.189417   
1469                    0.160313                    0.504003   
1470                    0.180688                   -0.209794   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
1466                 0.232695  ...                           -0.999736   
1467                 0.106566  ...                           -0.999414   
1468                -0.223721  ...                           -0.703363   
1469                -0.073582  ...                           -0.999296   
1470                -0.009915  ...                           -0.895324   

      fBodyAccJerk-bandsEnergy()-49,64.2  fBodyGyro-min()-Y  \
1466                           -0.999642          -0.993454   
1467                           -0.999498          -0.999391   
1468                           -0.260255          -0.793648   
1469                           -0.998998          -0.954967   
1470                           -0.884323          -0.799233   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
1466                        -0.999949                  -0.988987   
1467                        -0.999986                  -0.996189   
1468                        -0.771367                  -0.120213   
1469                        -0.999361                  -0.945335   
1470                        -0.927293                   0.076213   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
1466                      -1.000000                -0.993440   
1467                      -1.000000                -0.998003   
1468                       0.711324                -0.110976   
1469                      -0.798901                -0.946530   
1470                       0.710326                -0.361945   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
1466                   -0.995521                         0.166124   
1467                   -0.994214                         0.425059   
1468                   -0.553784                         0.187655   
1469                   -0.954411                        -0.200412   
1470                   -0.813583                         0.032252   

      angle(tBodyAccMean,gravity)  
1466                    -0.054788  
1467                     0.076333  
1468                     0.330378  
1469                    -0.048474  
1470                     0.374865  

[5 rows x 50 columns]

## 데이터 전처리

In [60]:
def target_morphs(data, target = None, target_dynamic = None):
    df = data.copy()
    # target이 지정되지 않았으면 가장 마지막 열로 지정
    if target is None:
        target = data.columns[-1]
    # targets가 존재하지만 리스트가 아니라면 리스트로 변경
    if target_dynamic is not None:
        if not isinstance(target_dynamic, list):
            target_dynamic = [target_dynamic]
        # target이 targets에 포함되는지 여부를 target에 저장
        df[target] = df[target].apply(lambda x: 0 if x in target_dynamic else 1)
    return df

In [30]:
data.tail()

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyGyro-min()-Y  \
5876                 0.419680  ...          -0.997983   
5877                -0.260559  ...          -0.951267   
5878                 0.155540  ...          -0.998177   
5879                -0.229386  ...          -0.687973   
5880                 0.505829  ...          -0.906829   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
5876                        -0.999967                  -0.987428   
5877                        -0.982422                  -0.561358   
5878                        -0.999920                  -0.989684   
5879                        -0.940509                  -0.465531   
5880                        -0.997315                  -0.979258   

      fBodyBodyAccJerkMag-entropy()  fBodyBodyGyroMag-mean()  \
5876                      -1.000000                -0.981119   
5877                       0.241367                -0.415217   
5878                      -1.000000                -0.991452   
5879                       0.323401                -0.504324   
5880                      -1.000000                -0.949917   

      fBodyBodyGyroJerkMag-min()  fBodyBodyGyroJerkMag-meanFreq()  \
5876                   -0.983765                         0.052914   
5877                   -0.845447                         0.325461   
5878                   -0.989032                         0.362439   
5879                   -0.867993                         0.031915   
5880                   -0.988100                         0.463038   

      angle(tBodyAccMean,gravity)          Activity  Activity_dynamic  
5876                    -0.034888           SITTING                 5  
5877                     0.721718  WALKING_UPSTAIRS                 1  
5878                     0.060173            LAYING                 3  
5879                     0.260880  WALKING_UPSTAIRS                 1  
5880                     0.107690           SITTING                 5  

[5 rows x 52 columns]

In [61]:
y = data[['Activity', 'Activity_dynamic']]
y

Activity  Activity_dynamic
0               STANDING                 4
1                 LAYING                 3
2               STANDING                 4
3                WALKING                 0
4     WALKING_DOWNSTAIRS                 2
...                  ...               ...
5876             SITTING                 5
5877    WALKING_UPSTAIRS                 1
5878              LAYING                 3
5879    WALKING_UPSTAIRS                 1
5880             SITTING                 5

[5881 rows x 2 columns]

In [62]:
target_morphs(data, 'Activity', ['STANDING', 'LAYING', 'SITTING'])

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
0             -0.103362               -0.094784               -0.109208   
1             -0.098163               -0.052478                0.464764   
2             -0.108717               -0.226718                0.301165   
3             -0.150354                0.549363               -0.384117   
4              0.091229               -0.091537               -0.610793   
...                 ...                     ...                     ...   
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
0                  0.068584              -0.014314   
1                  0.075947               0.004456   
2                  0.079530               0.014504   
3                 -0.309509              -0.201293   
4                  0.584212              -0.266815   
...                     ...                    ...   
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
0                       0.198600                   -0.073666   
1                       0.130310                    0.401913   
2                       0.111340                    0.263556   
3                       0.411714                   -0.372620   
4                      -0.248696                   -0.628852   
...                          ...                         ...   
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
0                       0.113098                   -0.058315   
1                       0.512569                    0.011987   
2                       0.562730                    0.314589   
3                       0.288349                   -0.259441   
4                       0.095282                   -0.240501   
...                          ...                         ...   
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyGyro-min()-Y  \
0                    0.354270  ...          -0.996607   
1                    0.503466  ...          -0.992681   
2                    0.132061  ...          -0.999971   
3                   -0.711894  ...          -0.876509   
4                   -0.305964  ...          -0.960097   
...                       ...  ...                ...   
5876                 0.419680  ...          -0.997983   
5877                -0.260559  ...          -0.951267   
5878                 0.155540  ...          -0.998177   
5879                -0.229386  ...          -0.687973   
5880                 0.505829  ...          -0.906829   

      fBodyGyro-bandsEnergy()-49,64.1  fBodyBodyAccJerkMag-iqr()  \
0                           -0.999969                  -0.985141   
1                           -0.999941                  -0.988982   
2                           -

In [63]:
from sklearn.metrics import classification_report, confusion_matrix

def score_model(data, random_state = None):
    X, y, lb = data_processing(data)
    x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = random_state)
    print('='*150)
    y_pred = double_model(x_train, y_train, x_test)
    print(classification_report(y_test['Activity_dynamic'], y_pred))
    print('='*150)
    # 썼던 라벨(lb)가 주어진다면
    if lb is not None:
        # LabelEncoder가 숫자형 범주로 바꾸는데 사용한 class들을 가져오고
        values = lb.classes_
        # 그걸 다시 LabelEncoder를 이용해 숫자로 바꿔서
        keys = lb.transform(lb.classes_)
        # 재결합해서 번역 Dict 생성
        dictionary = dict(zip(keys, values))
        for _ in range(len(dictionary)):
            # 그래서 Confusion Matrix를 보기 쉽게 출력
            print(dictionary[_], end=', ')
    print()
    print(confusion_matrix(y_test['Activity_dynamic'], y_pred))


In [64]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

def data_processing(data, target = 'Activity'):
    # target_dynamic 리스트에 들어있는 Activity는 0, 없으면 1
    df = target_morphs(data, target = target, target_dynamic = ['STANDING', 'LAYING', ' SITTING'])
    # Unused
    # ynum = len(lb.classes_)
    # 위의 is dynamic이 아닌 실제 값. morphs는 Activity를 덮어씌우게 만들어서 이렇게 따로 추가해 줘야 함.
    real_y = data['Activity_dynamic'].copy()
    # Activity_dynamic 에 저장
    df[f'{target}_dynamic'] = real_y
    target = [target, f'{target}_dynamic']
    X = df.drop(target, axis = 1)
    y = df[target]
    # lb를 반환하는 이유는 score_model에서
    return X, y, lb
X, y, lb = data_processing(data)
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 2023)

In [42]:
X

tBodyAcc-mean()-Z  tBodyAcc-arCoeff()-X,2  tBodyAcc-arCoeff()-Y,1  \
0             -0.103362               -0.094784               -0.109208   
1             -0.098163               -0.052478                0.464764   
2             -0.108717               -0.226718                0.301165   
3             -0.150354                0.549363               -0.384117   
4              0.091229               -0.091537               -0.610793   
...                 ...                     ...                     ...   
5876          -0.131974               -0.059080                0.000441   
5877          -0.105174                0.275170               -0.191391   
5878          -0.107440               -0.025156                0.407618   
5879          -0.121001                0.686123               -0.606018   
5880          -0.138018               -0.275424               -0.158631   

      tBodyAccJerk-mean()-X  tBodyAccJerk-mean()-Y  \
0                  0.068584              -0.014314   
1                  0.075947               0.004456   
2                  0.079530               0.014504   
3                 -0.309509              -0.201293   
4                  0.584212              -0.266815   
...                     ...                    ...   
5876               0.082392              -0.008733   
5877              -0.108297               0.050577   
5878               0.070742               0.011347   
5879              -0.085843              -0.039197   
5880               0.079556              -0.119456   

      tBodyAccJerk-arCoeff()-X,2  tBodyAccJerk-arCoeff()-Y,1  \
0                       0.198600                   -0.073666   
1                       0.130310                    0.401913   
2                       0.111340                    0.263556   
3                       0.411714                   -0.372620   
4                      -0.248696                   -0.628852   
...                          ...                         ...   
5876                    0.180157                    0.041011   
5877                    0.168315                   -0.313497   
5878                    0.222424                    0.259452   
5879                    0.499451                   -0.628068   
5880                    0.027651                   -0.051177   

      tBodyAccJerk-arCoeff()-Y,3  tBodyAccJerk-arCoeff()-Z,1  \
0                       0.113098                   -0.058315   
1                       0.512569                    0.011987   
2                       0.562730                    0.314589   
3                       0.288349                   -0.259441   
4                       0.095282                   -0.240501   
...                          ...                         ...   
5876                    0.173103                   -0.001160   
5877                   -0.067457                   -0.006740   
5878                    0.497603                    0.187073   
5879                    0.337687                   -0.037529   
5880                    0.118587                    0.160995   

      tBodyGyro-arCoeff()-Z,3  ...  fBodyAccJerk-bandsEnergy()-41,48.2  \
0                    0.354270  ...                           -0.999669   
1                    0.503466  ...                           -0.999818   
2                    0.132061  ...                           -0.999566   
3                   -0.711894  ...                           -0.940882   
4                   -0.305964  ...                           -0.983249   
...                       ...  ...                                 ...   
5876                 0.419680  ...                           -0.999479   
5877                -0.260559  ...                           -0.956513   
5878                 0.155540  ...                           -0.999504   
5879                -0.229386  ...                           -0.959061   
5880                 0.505829  ...                           -0.999014   

      fBodyAccJerk-bandsEnerg

## 3. 단계별 모델링

In [65]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier()
model1.fit(x_train, y_train.drop('Activity_dynamic', axis = 1))
y1_pred = model1.predict(x_train)
x_train_a = x_train.iloc[y1_pred == 0]
x_train_b = x_train.iloc[y1_pred == 1]

<ipython-input-65-97817d10191f>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(x_train, y_train.drop('Activity_dynamic', axis = 1))


In [66]:
x_train[:10].index, x_train_a[:10].index, x_train_b[:10].index, y1_pred[:10]

(Int64Index([1313, 5747, 5262, 1949, 1780, 3296, 2035, 5072, 455, 5715], dtype='int64'),
 Int64Index([3296, 2035, 5715, 2418, 5455, 4006, 1613, 2099, 750, 688], dtype='int64'),
 Int64Index([1313, 5747, 5262, 1949, 1780, 5072, 455, 3254, 1343, 2145], dtype='int64'),
 array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0]))

In [67]:
model2 = RandomForestClassifier()
model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])

<ipython-input-67-2ec187c61a67>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])


RandomForestClassifier()

In [68]:
model3 = RandomForestClassifier()
model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])

<ipython-input-68-751b08850619>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])


RandomForestClassifier()

In [69]:
def double_model(x_train, y_train, data):
    # 1차 분류
    model1 = RandomForestClassifier()
    model1.fit(x_train, y_train.drop('Activity_dynamic', axis=1))
    # 분류 예측 결과
    y1_pred = model1.predict(x_train)
    # 0이면 여기에
    x_train_a = x_train.iloc[y1_pred == 0]
    # 1이면 여기에
    x_train_b = x_train.iloc[y1_pred == 1]
    # 0 -> 0, 1, 2 분류
    model2 = RandomForestClassifier()
    model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])
    # 1 -> 3, 4, 5 분류
    model3 = RandomForestClassifier()
    model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])

    temp = model1.predict(data)
    # 원본 순서를 저장
    idx = data.index
    # 데이터 분리
    data_a = data.iloc[temp == 0]
    data_b = data.iloc[temp == 1]
    ans_a = pd.DataFrame({'answer':model2.predict(data_a)}, index = data_a.index)
    ans_b = pd.DataFrame({'answer':model3.predict(data_b)}, index = data_b.index)
    # 결과 합치기
    ans = pd.concat([ans_a, ans_b])
    # 들어온 데이터 순서대로 재정렬해서 반환
    return ans.loc[idx]

In [70]:
y_test

Activity  Activity_dynamic
5574         1                 0
2078         0                 4
1579         0                 3
4585         1                 5
5384         0                 3
...        ...               ...
3457         0                 4
351          0                 4
4997         0                 3
2387         0                 4
2762         1                 5

[1177 rows x 2 columns]

In [71]:
score_model(data, 2023)

<ipython-input-69-5c3457c811e0>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(x_train, y_train.drop('Activity_dynamic', axis=1))
<ipython-input-69-5c3457c811e0>:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model2.fit(x_train_a, y_train.drop('Activity', axis=1).iloc[y1_pred == 0])
<ipython-input-69-5c3457c811e0>:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(x_train_b, y_train.drop('Activity', axis=1).iloc[y1_pred == 1])


              precision    recall  f1-score   support

           0       0.74      0.80      0.77       180
           1       0.80      0.75      0.77       175
           2       0.81      0.78      0.79       165
           3       0.60      0.83      0.70       230
           4       0.56      0.80      0.66       218
           5       0.78      0.12      0.21       209

    accuracy                           0.67      1177
   macro avg       0.71      0.68      0.65      1177
weighted avg       0.71      0.67      0.64      1177

LAYING, SITTING, STANDING, WALKING, WALKING_DOWNSTAIRS, WALKING_UPSTAIRS, 
[[144  17  19   0   0   0]
 [ 31 132  12   0   0   0]
 [ 20  16 129   0   0   0]
 [  0   1   0 190  34   5]
 [  0   0   0  42 174   2]
 [  0   0   0  84 100  25]]


In [72]:
RFmodel = RandomForestClassifier()
RFmodel.fit(x_train, y_train.drop('Activity', axis = 1))
RFmodel.score(x_test, y_test.drop('Activity', axis = 1))
y_pred = RFmodel. predict(x_test)
print(classification_report(y_test['Activity_dynamic'], y_pred))
print(confusion_matrix(y_test['Activity_dynamic'], y_pred))

<ipython-input-72-bb58bbaf0805>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFmodel.fit(x_train, y_train.drop('Activity', axis = 1))


              precision    recall  f1-score   support

           0       0.70      0.78      0.74       180
           1       0.78      0.74      0.76       175
           2       0.79      0.73      0.76       165
           3       0.67      0.77      0.72       230
           4       0.66      0.71      0.68       218
           5       0.59      0.45      0.51       209

    accuracy                           0.69      1177
   macro avg       0.70      0.70      0.69      1177
weighted avg       0.69      0.69      0.69      1177

[[140  19  21   0   0   0]
 [ 34 129  12   0   0   0]
 [ 26  18 121   0   0   0]
 [  0   0   0 178  22  30]
 [  0   0   0  29 154  35]
 [  0   0   0  58  57  94]]


In [73]:
# test dataset 학습
y_pred = RFmodel. predict(test)


In [55]:
y_pred

array([2, 2, 3, ..., 4, 0, 4])

In [74]:
# y_pred 배열을 Activity 열로 구성된 데이터프레임으로 변환
result_df = pd.DataFrame({'Activity': y_pred})

# ID 열 추가
result_df.insert(0, 'ID', test.index)

# 결과 확인
print(result_df.head())

   ID  Activity
0   0         5
1   1         4
2   2         0
3   3         5
4   4         3


In [75]:
result_df.to_csv(path + 'RF모델.csv', index=False)

In [ ]:
test.drop('')

In [29]:
y_pred = RFmodel.predict(test)

ValueError: ignored

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pickle

# 저장된 모델 로드
with open('/content/sample_data/random_forest_model.pkl', 'rb') as f:
    loaded_RFmodel = pickle.load(f)

# 테스트 데이터 예측
y_pred = loaded_RFmodel.predict(x_test)

# 모델 평가
print(classification_report(y_test['Activity2'], y_pred))
print(confusion_matrix(y_test['Activity2'], y_pred))
