# **차량 공유업체의 차량 파손 여부 분류하기**

## 0.미션

* 1) 미션1 : Data Preprocessing
    - **과제 수행 목표**
        - 본인의 구글 드라이브에 모델링 수행을 위해 적절한 폴더 및 파일로 **일관성 있게 정리**해야 합니다.
        - 제공된 데이터 : Car_Images.zip
            * Car_Images : 차량의 정상/파손 이미지 무작위 수집

* 2) 미션2 : CNN 모델링
    - **과제 수행 목표**
        - Tensorflow Keras를 이용하여 모델을 3개 이상 생성하세요.
            - 모델 구조와 파라미터는 자유롭게 구성하세요.
            - 단, 세부 목차에서 명시한 부분은 지켜주세요.

* 3) 미션3 : Data Argumentation & Transfer Learning
    - **과제 수행 목표**
        - 성능 개선을 위해 다음의 두가지를 시도하세요.
            * Data Augmentation을 적용하세요.(Image Generator)
            * Transfer Learning(VGG16)


## 1.환경설정 

### (1) 데이터셋 폴더 생성
- **세부요구사항**
    - C드라이브에 Datasets라는 폴더를 만드세요.
        - 구글드라이브를 사용하는경우 드라이브 첫 화면에 Datasets 라는 폴더를 만드세요. ('/content/drive/MyDrive/Datasets/')
    - 해당 폴더 안에 Car_Images.zip 파일을 넣으세요.

* 구글 Colab을 이용하는 경우

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### (2) 데이터셋 불러오기 
- **세부요구사항**
    - Car_Images.zip 파일을 C:/Datasets/ 경로에 압축 해제합니다.
    - zipfile 모듈을 이용하거나 다른 방식을 사용해도 됩니다.
        - 참고 자료 : [zipfile document](https://docs.python.org/3/library/zipfile.html#zipfile-objects)
    - 폴더구조(로컬)
        * C:/Datasets/ : 압축파일
        * C:/Datasets/Car_Images_train/ : 압축 해제한 이미지 저장소
    - 폴더구조(구글드라이브브)
        * /content/drive/MyDrive/Datasets/ : 압축파일
        * /content/drive/MyDrive/Datasets/Car_Images_train/ : 압축 해제한 이미지 저장소
    - 압축을 해제하면 다음과 같은 두 하위 폴더가 생성됩니다.
        * normal, abnormal : 각 폴더에는 이미지들이 있습니다.
        * 이후 단계에서 해당 경로로 부터 validation, test 셋을 추출하게 됩니다.
        

In [ ]:
import zipfile

In [3]:
# 압축파일 경로
# 구글 드라이브인 경우 경로에 맞게 지정하세요.
dataset_path  = '/content/drive/MyDrive/Datasets/'
#dataset_path = 'C:/Datasets/'

file_path = dataset_path + 'Car_Images'

In [ ]:
# 압축 해제


### (3) 이미지 저장을 위한 폴더 생성
- **세부요구사항**
    - train, validation, test 을 위해 각각 하위 폴더 normal과 abnormal를 준비합니다.
        - train
            * 정상 이미지 저장소 : C:/Datasets/Car_Images_train/normal/ 
                * 구글드라이브 :   /content/drive/MyDrive/Datasets/Car_Images_train/normal/
            * 파손 이미지 저장소 : C:/Datasets/Car_Images_train/abnormal/
                * 구글드라이브 : /content/drive/MyDrive/Datasets/Car_Images_train/abnormal/
        - val, test 역시 동일한 구조로 생성합니다.
    - 직접 탐색기에서 폴더를 생성할 수도 있고, os 모듈을 이용하여 코드로 작성할 수도 있습니다.
        - 참고 자료 : [os document](https://docs.python.org/3/library/os.html)

In [ ]:

# 각각 경로 지정



# train 폴더는 압축을 해제하면서 이미 생성 되어 있습니다.

# test 폴더 만들기 os.mkdir()



# validation 폴더 만들기



## 2.데이터 전처리

### (1) 데이터 분할 : Training set | Validation set | Test set 생성
- **세부요구사항**
    - Training set, Validation set, Test set을 만듭니다.
        * size
            * test : 전체에서 20%를 추출합니다.
            * validation : test를 떼어낸 나머지에서 다시 20%를 추출합니다.
        * 데이터는 랜덤하게 추출해야 합니다.
            - random, shutil 모듈을 이용하여 랜덤하게 추출할 수 있습니다.
                - [random document](https://docs.python.org/3/library/random.html) | [shutil document](https://docs.python.org/3/library/shutil.html)
            * 해당 모듈 이외에 자신이 잘 알고 있는 방법을 사용해도 됩니다.
---

#### 1) test, validation 크기를 지정

In [3]:
import random, shutil, os
import numpy as np

In [ ]:
 tr_n_path = '/content/drive/MyDrive/Datasets/Car_Images_train/normal/'
tr_ab_path= '/content/drive/MyDrive/Datasets/Car_Images_train/abnormal/'
test_n_path = '/content/drive/MyDrive/Datasets/Car_Images_test/normal/'
test_ab_path= '/content/drive/MyDrive/Datasets/Car_Images_test/abnormal/'
val_n_path = '/content/drive/MyDrive/Datasets/Car_Images_val/normal/'
val_ab_path= '/content/drive/MyDrive/Datasets/Car_Images_val/abnormal/'
n_path='/content/drive/MyDrive/Datasets/Car_Images/normal'
ab_path='/content/drive/MyDrive/Datasets/Car_Images/abnormal'
os.listdir(tr_n_path)

In [ ]:
# 전체 이미지 갯수를 확인합니다.
len(os.listdir(tr_n_path)) , len(os.listdir(tr_ab_path))

(302, 303)

In [ ]:
# test 사이즈 : 전체 이미지의 20%
te_data_num = [round(len(os.listdir(tr_n_path))*0.2), round(len(os.listdir(tr_ab_path))*0.2)]
print(te_data_num)

# validation 사이즈 : test를 제외한 나머지 중에서 20%
val_data_num = [ round((len(os.listdir(tr_n_path))-te_data_num[0])*0.2) , round((len(os.listdir(tr_n_path))-te_data_num[1])*0.2) ]
print(val_data_num)

# train 사이즈
train_data_num = [len(os.listdir(tr_n_path)) - te_data_num[0] - val_data_num[0],
                  len(os.listdir(tr_ab_path))- te_data_num[1] - val_data_num[1]]
print(train_data_num)

[60, 61]
[48, 48]
[194, 194]


In [ ]:
img_n_list = os.listdir(tr_n_path)
img_ab_list = os.listdir(tr_ab_path)

['DALL¡¤E 2023-03-10 22.22.12 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.50.29 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.52.44 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.50.25 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.52.35 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.50.18 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 22.07.10 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.52.40 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 22.07.07 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.50.11 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.52.17 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 18.52.13 - photo of a part of car.png', 'DALL¡¤E 2023-03-10 23.32.22 - photo of a part of car without blemish.png', 'DALL¡¤E 2023-03-10 23.31.15 - photo of a part of car without blemish.png', 'DALL¡¤E 2023-03-10 23.33.39 - photo of a part of car without blemish.png', 'DALL¡¤E 2023-03-10 23.32.16 - photo of a part of c

In [ ]:
random.seed(2023)
random.shuffle(img_n_list)
random.shuffle(img_ab_list)

#### 2) test 셋 추출

In [ ]:
test_n_list = img_n_list[:te_data_num[0]]
test_ab_list = img_ab_list[:te_data_num[1]]

test_list =test_n_list+test_ab_list

In [ ]:
print(len(test_n_list))
print(len(test_ab_list))

60
61


In [ ]:
for img_name in test_n_list:
    src_path = os.path.join(tr_n_path, img_name)
    dst_path = os.path.join(test_n_path, img_name)
    shutil.copy(src_path, dst_path)

FileNotFoundError: ignored

In [ ]:
for img_name in test_ab_list:
    src_path = os.path.join(tr_ab_path, img_name)
    dst_path = os.path.join(test_ab_path, img_name)
    shutil.copy(src_path, dst_path)

In [ ]:
print(len(test_list))

In [ ]:
# 추출 후 이미지 갯수 확인
print(len(val_n_list))
print(len(val_ab_list))

48
48


#### 3) validation 셋 추출

In [ ]:
val_n_list = img_n_list[te_data_num[0]:val_data_num[0]+te_data_num[0]]
val_ab_list = img_ab_list[te_data_num[1]:val_data_num[1]+te_data_num[1]]
val_list=val_n_list+val_ab_list

In [ ]:
# 추출 후 이미지 갯수 확인
# print(val_n_list)
print(len(val_n_list))
print(len(val_ab_list))

48
48


In [ ]:
train_n_list = img_n_list[val_data_num[0]+te_data_num[0]:]
train_ab_list = img_ab_list[val_data_num[1]+te_data_num[1]:]
train_list=train_n_list+train_ab_list

In [ ]:
print(len(train_n_list))
print(len(train_ab_list))

194
194


In [ ]:
for img_name in val_n_list:
    src_path = os.path.join(tr_n_path, img_name)
    dst_path = os.path.join(val_n_path, img_name)
    shutil.copy(src_path, dst_path)

In [ ]:
for img_name in val_ab_list:
    src_path = os.path.join(tr_ab_path, img_name)
    dst_path = os.path.join(val_ab_path, img_name)
    shutil.copy(src_path, dst_path)

In [ ]:
len(train_list)


387

In [ ]:
for img_name in train_n_list:
    src_path = os.path.join(n_path, img_name)
    dst_path = os.path.join(tr_n_path, img_name)
    shutil.copy(src_path, dst_path)


In [ ]:
for img_name in train_ab_list:
    src_path = os.path.join(ab_path, img_name)
    dst_path = os.path.join(tr_ab_path, img_name)
    shutil.copy(src_path, dst_path)

In [ ]:

print(len(os.listdir(tr_n_path)))
print(len(os.listdir(tr_ab_path)))
print(len(os.listdir(test_n_path)))
print(len(os.listdir(test_ab_path)))
print(len(os.listdir(val_n_path)))
print(len(os.listdir(val_ab_path)))
print(len(os.listdir(n_path)))
print(len(os.listdir(ab_path)))

194
194
60
61
48
48
302
303


### (2) 데이터 복사 및 이동
- **세부요구사항**
    - 분할된 데이터를 복사 이동합니다.
        - 새로운 폴더에 저장하는 데이터로 "3.모델링I"에서 사용합니다.
        - 기존 폴더는 "4.모델링II > (1) Data Augmentation"에서 사용합니다.
    - Training set | Validation set | Test set의 데이터를 **새로운 폴더**에 복사하세요.
        - 새로운 폴더 명
            * copy_images/trainset
            * copy_images/validset
            * copy_images/testset
        - 새로운 폴더에는 normal, abnormal 파일 모두를 복사합니다. 
            * 파일을 구분하기 위해 abnormal 파일들은 파일명 앞에 접두사 'ab_'를 붙입시다.
        - os, shutil 모듈을 활용하세요.

#### 1) abnormal 파일 복사

#### 2) normal 파일 복사

* 복사하기 : shutil.copytree()

In [ ]:
copy_test_path='/content/drive/MyDrive/Datasets/copy_images/testset'
copy_train_path='/content/drive/MyDrive/Datasets/copy_images/trainset'
copy_val_path='/content/drive/MyDrive/Datasets/copy_images/validset'

In [ ]:
data=[tr_n_path, tr_ab_path, test_n_path, test_ab_path, val_n_path, val_ab_path]
for i in range(6):
    for img_name in os.listdir(data[i]):
        src_path = os.path.join(data[i], img_name)
        if i == 0 or i== 1:
            dst_path = os.path.join(copy_train_path, img_name)
        elif i== 2 or i==3:
            dst_path = os.path.join(copy_test_path, img_name)
        else:
            dst_path = os.path.join(copy_val_path, img_name)

        shutil.copy(src_path, dst_path)

* abnormal 이미지 이름의 접두어 "ab_" 붙이기 : os.rename

* 데이터 갯수 조회

In [ ]:
print(len(os.listdir(dataset_path+'copy_images/trainset/')))
print(len(os.listdir(dataset_path+'copy_images/validset/')))
print(len(os.listdir(dataset_path+'copy_images/testset/')))

388
96
121


## 3.모델링 I
* **세부요구사항**
    * 모델링을 위한 데이터 구조 만들기
        * x : 이미지를 array로 변환합니다.
        * y : 이미지 갯수만큼 normal - 0, abnormal - 1 로 array를 만듭니다.
    * 모델을 최소 3개 이상 만들고 성능을 비교합니다.
        * 모델 학습 과정에 알맞은 보조 지표를 사용하세요.
        * 전처리 과정에서 생성한 Validation set을 적절하게 사용하세요.
        * Early Stopping을 반드시 사용하세요.
            * 최적의 가중치를 모델에 적용하세요.

In [12]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix

In [13]:
import random, shutil, os
import numpy as np

### (1) X : image to array
- **세부요구사항**
    * 모델링을 위해서는 np.array 형태로 데이터셋을 만들어야 합니다.
    * Training set / Validation set / Test set의 X는 이미지 형태로 되어있습니다. 
    * 이미지 파일을 불러와 train, valid, test 각각 array 형태로 변환해 봅시다.
        * 각 폴더로 부터 이미지 목록을 만들고
        * 이미지 한장씩 적절한 크기로 로딩하여 (keras.utils.load_img)
            * 이미지가 너무 크면 학습시간이 많이 걸리고, 메모리 부족현상이 발생될 수 있습니다.
            * 이미지 크기를 280 * 280 * 3 이내의 크기를 설정하여 로딩하시오.
            * array로 변환 (keras.utils.img_to_array, np.expand_dims)
        * 데이터셋에 추가합니다.(데이터셋도 array)

#### 1) 이미지 목록 만들기
* train, validation, test 폴더로 부터 이미지 목록을 생성합니다.

In [7]:
import os

In [8]:
# 이미지 목록 저장
img_train_list = os.listdir(dataset_path+'copy_images/trainset/')
img_valid_list = os.listdir(dataset_path+'copy_images/validset/')
img_test_list = os.listdir(dataset_path+'copy_images/testset/')

In [9]:
# 메모리, 처리시간을 위해서 이미지 크기 조정
img_size = 280 ## 사이즈 조정 가능

In [10]:
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array

#### 2) 이미지들을 배열 데이터셋으로 만들기

In [96]:
images = []
labels = []

for path in img_train_list:
    img = load_img(dataset_path+'copy_images/trainset/'+path)
    img = img.resize((280,280))
    img = img_to_array(img)
    
    images.append(img)

x_train = np.array(images)

print(x_train.shape)

(388, 280, 280, 3)


In [97]:
images = []
labels = []

for path in img_test_list:
    img = load_img(dataset_path+'copy_images/testset/'+path)
    img = img.resize((280,280))
    img = img_to_array(img)
    
    images.append(img)

x_test = np.array(images)

print(x_test.shape)

(121, 280, 280, 3)


In [98]:
images = []
labels = []

for path in img_valid_list:
    img = load_img(dataset_path+'copy_images/validset/'+path)
    img = img.resize((280,280))
    img = img_to_array(img)
    
    images.append(img)

x_val = np.array(images)

print(x_val.shape)

(96, 280, 280, 3)


### (2) y : 클래스 만들기
- **세부요구사항**
    - Training set / Validation set / Test set의 y를 생성합니다.
        - 각각 normal, abnormal 데이터의 갯수를 다시 확인하고
        - normal을 0, abnormal을 1로 지정합니다.

In [17]:
# 데이터 갯수 확인
print( len(img_train_list) )
print( len([val for val in img_train_list if val.startswith('ab_')]) )
print('---')
print( len(img_valid_list) )
print( len([val for val in img_valid_list if val.startswith('ab_')]) )
print('---')
print( len(img_test_list) )
print( len([val for val in img_test_list if val.startswith('ab_')]) )

388
194
---
96
48
---
121
61


* y_train, y_valid, y_test 만들기
    * normal, abnormal 데이터의 갯수를 다시 확인하고 normal을 0, abnormal을 1로 지정합니다.

In [18]:
y_train=[]
for i in img_train_list :
    if i.startswith('ab_'):
        y_train.append(1)
    else:
        y_train.append(0)

y_train=np.array(y_train)

In [19]:
y_val=[]
for i in img_valid_list :
    if i.startswith('ab_'):
        y_val.append(1)
    else:
        y_val.append(0)

y_val=np.array(y_val)

In [20]:
y_test=[]
for i in img_test_list :
    if i.startswith('ab_'):
        y_test.append(1)
    else:
        y_test.append(0)

y_test=np.array(y_test)

In [21]:
print(y_train.shape, y_test.shape, y_val.shape)

(388,) (121,) (96,)


### (3) 모델1
- **세부요구사항**
    - Conv2D, MaxPooling2D, Flatten, Dense 레이어들을 이용하여 모델을 설계
    - 학습시 validation_data로 validation set을 사용하시오.
    - 반드시 Early Stopping 적용
    - 평가시, confusion matrix, accuracy, recall, precision, f1 score 등을 이용하시오.

min-max scaling

In [ ]:
min_n, max_n = x_train.min(), x_train.max()
x_train = (x_train - min_n) / (max_n - min_n)
x_test = (x_test - min_n) / (max_n - min_n)
x_val = (x_val - min_n) / (max_n - min_n)

to_categorical

In [22]:
class_n = len(np.unique(y_train))

In [23]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, class_n)
y_test = to_categorical(y_test, class_n)
y_val = to_categorical(y_val, class_n)

스탠다드


In [103]:
mean_n = x_train.mean()
std_n = x_train.std()

x_train = (x_train - mean_n) / std_n
x_test = (x_test - mean_n) / std_n
x_val = (x_val - mean_n) / std_n

In [25]:
x_test .mean(), x_test.std()

(0.08334001, 1.0730253)

#### 1) 구조 설계

In [38]:
from tensorflow.keras.backend import clear_session
from tensorflow.keras.layers import Dense, Input, Flatten, BatchNormalization, Dropout, Conv2D, AvgPool2D
from tensorflow.keras.models import Model

#### 2) 학습
* EarlyStopping 설정하고 학습시키기

In [26]:
from tensorflow.keras.callbacks import EarlyStopping

In [27]:
es = EarlyStopping(monitor = 'val_loss',
                   min_delta = 0,
                   patience = 15,
                   verbose = 1)

In [28]:
x_train.shape, y_train.shape

((388, 280, 280, 3), (388, 2))

#### 3) test set으로 예측하고 평가하기
* 평가는 confusion_matrix, classification_report 활용

# 데이터를 넣어서 학습시키자!
history = model.fit(x_train, y_train,
                    epochs = 10000, verbose = 1,
                    callbacks = [es], validation_data =(x_val,y_val))

In [47]:
######################
#########주현#########
######################
import tensorflow as tf

model_path='/content/drive/MyDrive/Datasets/first_model.h5'
# 모델 파일 불러오기
model = tf.keras.models.load_model(model_path)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 278, 278, 16)      448       
                                                                 
 conv2d_1 (Conv2D)           (None, 276, 276, 16)      2320      
                                                                 
 conv2d_2 (Conv2D)           (None, 274, 274, 16)      2320      
                                                                 
 batch_normalization (BatchN  (None, 274, 274, 16)     64        
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 137, 137, 16)     0         
 )                                                               
                                                                 
 conv2d_3 (Conv2D)           (None, 135, 135, 32)      4

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(x_test)
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)
print(confusion_matrix(single_test_y, single_y_pred))
print(classification_report(single_test_y, single_y_pred))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 278, 278, 16)      448       
                                                                 
 conv2d_1 (Conv2D)           (None, 276, 276, 16)      2320      
                                                                 
 conv2d_2 (Conv2D)           (None, 274, 274, 16)      2320      
                                                                 
 batch_normalization (BatchN  (None, 274, 274, 16)     64        
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 137, 137, 16)     0         
 )                                                               
                                                                 
 conv2d_3 (Conv2D)           (None, 135, 135, 32)      4

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 278, 278, 16)      448       
                                                                 
 conv2d_1 (Conv2D)           (None, 276, 276, 16)      2320      
                                                                 
 conv2d_2 (Conv2D)           (None, 274, 274, 16)      2320      
                                                                 
 batch_normalization (BatchN  (None, 274, 274, 16)     64        
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 137, 137, 16)     0         
 )                                                               
                                                                 
 conv2d_3 (Conv2D)           (None, 135, 135, 32)      4

In [32]:
######################
#########세연#########
######################
import tensorflow as tf

model_path='/content/drive/MyDrive/Datasets/Lenet(0.87).h5'
# 모델 파일 불러오기
model = tf.keras.models.load_model(model_path)

from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(x_test)``
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)
print(confusion_matrix(single_test_y, single_y_pred))
print(classification_report(single_test_y, single_y_pred))

4/4 [==============================] - 0s 21ms/step
(121, 2)
(121,)
[[58  2]
 [10 51]]
              precision    recall  f1-score   support

           0       0.85      0.97      0.91        60
           1       0.96      0.84      0.89        61

    accuracy                           0.90       121
   macro avg       0.91      0.90      0.90       121
weighted avg       0.91      0.90      0.90       121



In [46]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 280, 280, 3)]     0         
                                                                 
 conv2d (Conv2D)             (None, 280, 280, 6)       456       
                                                                 
 average_pooling2d (AverageP  (None, 140, 140, 6)      0         
 ooling2D)                                                       
                                                                 
 batch_normalization (BatchN  (None, 140, 140, 6)      24        
 ormalization)                                                   
                                                                 
 conv2d_1 (Conv2D)           (None, 136, 136, 16)      2416      
                                                                 
 average_pooling2d_1 (Averag  (None, 68, 68, 16)       0     

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(x_test)
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)
print(confusion_matrix(single_test_y, single_y_pred))
print(classification_report(single_test_y, single_y_pred))

4/4 [==============================] - 0s 77ms/step
(121, 2)
(121,)
[[52  8]
 [38 23]]
              precision    recall  f1-score   support

           0       0.58      0.87      0.69        60
           1       0.74      0.38      0.50        61

    accuracy                           0.62       121
   macro avg       0.66      0.62      0.60       121
weighted avg       0.66      0.62      0.60       121



### (4) 모델2
- **세부요구사항**
    - Conv2D, MaxPooling2D, Flatten, Dense 레이어들을 이용하여 모델을 설계
    - 학습시 validation_data로 validation set을 사용하시오.
    - 반드시 Early Stopping 적용
    - 평가시, confusion matrix, accuracy, recall, precision, f1 score 등을 이용하시오.

#### 1) 구조 설계

#### 2) 학습
* EarlyStopping 설정하고 학습시키기

#### 3) test set으로 예측하고 평가하기
* 평가는 confusion_matrix, classification_report 활용

### (5) 모델3
- **세부요구사항**
    - Conv2D, MaxPooling2D, Flatten, Dense 레이어들을 이용하여 모델을 설계
    - 학습시 validation_data로 validation set을 사용하시오.
    - 반드시 Early Stopping 적용
    - 평가시, confusion matrix, accuracy, recall, precision, f1 score 등을 이용하시오.

#### 1) 구조 설계

#### 2) 학습
* EarlyStopping 설정하고 학습시키기

#### 3) test set으로 예측하고 평가하기
* 평가는 confusion_matrix, classification_report 활용

## 4.모델링 II
* **세부요구사항**
    - 성능을 높이기 위해서 다음의 두가지를 시도해 봅시다.
        - Data Augmentation을 통해 데이터를 증가 시킵니다.
            - ImageDataGenerator를 사용합니다.
        - 사전 학습된 모델(Transfer Learning)을 가져다 사용해 봅시다.
            - VGG16(이미지넷)을 사용해 봅시다.

### (1) Data Augmentation
- **세부요구사항**
    * 모델 학습에 이용할 이미지 데이터를 증강시키세요.
    * Keras의 ImageDataGenerator를 이용
        - [ImageDataGenerator document](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator)

    * image generator를 이용하여 학습
        * 모델 구조는 이미 생성한 1,2,3 중 하나를 선택하여 학습


In [4]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [11]:
img_size = 280 ## 사이즈 조정 가능

train_path = dataset_path+'Car_Images_train/'
valid_path = dataset_path+'Car_Images_val/'

#### 1) ImageGenerator 생성
* ImageDataGenerator 함수 사용
    * 주요 옵션
        * rotation_range: 무작위 회전을 적용할 각도 범위
        * zoom_range: 무작위 줌을 적용할 범위 [1-zoom_range, 1+zoom_range]
        * horizontal_flip: 무작위 좌우반전을 적용할지 여부
        * vertical_flip: 무작위 상하반전을 적용할지 여부
        * rescale: 텐서의 모든 값을 rescale 값으로 나누어줌 (이 경우에는 255로 나누어서 0~1사이의 값으로 변경)

In [37]:
train_datagen =  ImageDataGenerator(
                    rotation_range=10,
                    width_shift_range=0.1,
                    height_shift_range=0.1,
                    shear_range=0.1,
                    zoom_range=0.1,
                    fill_mode ='wrap'
                    )

valid_datagen =   ImageDataGenerator(
                    rotation_range=10,
                    width_shift_range=0.1,
                    height_shift_range=0.1,
                    shear_range=0.1,
                    zoom_range=0.1,
                    fill_mode ='wrap'
                    )


#### 2) 경로로 부터 이미지 불러 올 준비
* .flow_from_directory 이용
    * 디렉토리에서 이미지를 가져와서 데이터 증강을 적용하고 batch 단위로 제공하는 generator를 생성합니다.
    * 이미지를 불러올 때 target_size로 크기를 맞추고, 
    * class_mode로 이진 분류(binary)를 수행하도록 지정합니다.


In [39]:
train_generator = train_datagen.flow_from_directory(directory = train_path,
                                                   target_size = (280,280),
                                                   class_mode = 'categorical',
                                                   shuffle = True)


valid_generator = valid_datagen.flow_from_directory(directory=valid_path,
                                                 target_size = (280, 280),
                                                 class_mode = 'categorical',
                                                 shuffle = True)


Found 388 images belonging to 3 classes.
Found 96 images belonging to 3 classes.


In [36]:
history = model.fit(train_generator,
                    epochs = 10000, verbose = 1,batch_size = 100,
                    callbacks = [es], validation_data = [valid_generator])

Epoch 1/10000


InvalidArgumentError: ignored

#### 3) 학습
- **세부요구사항**
    - Conv2D, MaxPooling2D, Flatten, Dense 레이어들을 이용하여 모델을 설계
    - 학습시 train_generator 이용. 
    - validation_data = valid_generator 지정
    - Early Stopping 적용
    - 평가시, confusion matrix, accuracy, recall, precision, f1 score 등을 이용하시오.

* 구조 설계

* 학습
    * EarlyStopping 설정하기
    * 학습 데이터에 train_generator, validation_data=valid_generator 사용

#### 4) 성능 평가
* 평가는 confusion_matrix, classification_report 활용

In [ ]:
######################
#########효국#########
######################
import tensorflow as tf

model_path='/content/drive/MyDrive/Datasets/first_model.h5'
# 모델 파일 불러오기
model = tf.keras.models.load_model(model_path)

from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(x_test)
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)
print(confusion_matrix(single_test_y, single_y_pred))
print(classification_report(single_test_y, single_y_pred))

4/4 [==============================] - 0s 32ms/step
(121, 2)
(121,)
[[51  9]
 [18 43]]
              precision    recall  f1-score   support

           0       0.74      0.85      0.79        60
           1       0.83      0.70      0.76        61

    accuracy                           0.78       121
   macro avg       0.78      0.78      0.78       121
weighted avg       0.78      0.78      0.78       121



In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
idg = ImageDataGenerator(rotation_range=20,
                         width_shift_range=0.1,
                         height_shift_range=0.1,
                         zoom_range=0.1,
                         shear_range=0.1,
                         horizontal_flip=True,
                         vertical_flip=True)

idg.fit(x_train)

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D, concatenate, Dropout, Flatten

model_path = '/content/drive/MyDrive/Datasets/first_model.h5'
model = tf.keras.models.load_model(model_path)

inputs = model.input

# 인셉션 레이어 추가
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, concatenate

# 첫번째 브랜치
branch_a = Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
branch_a = MaxPooling2D((2, 2), strides=(2, 2), padding='same')(branch_a)

# 두번째 브랜치
branch_b = Conv2D(32, (1, 1), activation='relu', padding='same')(inputs)
branch_b = Conv2D(32, (3, 3), activation='relu', padding='same')(branch_b)
branch_b = MaxPooling2D((2, 2), strides=(2, 2), padding='same')(branch_b)

# 세번째 브랜치
branch_c = Conv2D(32, (1, 1), activation='relu', padding='same')(inputs)
branch_c = Conv2D(32, (5, 5), activation='relu', padding='same')(branch_c)
branch_c = MaxPooling2D((2, 2), strides=(2, 2), padding='same')(branch_c)

# 네번째 브랜치
branch_d = AveragePooling2D((3, 3), strides=(1, 1), padding='same')(inputs)
branch_d = Conv2D(32, (1, 1), activation='relu', padding='same')(branch_d)
branch_d = MaxPooling2D((2, 2), strides=(2, 2), padding='same')(branch_d)  

# 모든 브랜치를 결합
x = concatenate([branch_a, branch_b, branch_c, branch_d])

# 추가 레이어
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
outputs = Dense(2, activation='sigmoid')(x)

# 인셉션 모델 생성
inception_model = Model(inputs=model.input, outputs=outputs)

# 기존 모델의 출력을 인셉션 모델의 입력으로 사용
outputs = inception_model(inputs=model.input)

# 새로운 모델 생성
model = Model(inputs=model.input, outputs=outputs)

In [ ]:
single_test_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
print(single_test_y.shape, single_y_pred.shape)

(121,) (121, 140, 2)


In [ ]:
y_pred.shape

(121, 140, 140, 2)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(x_test)
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)

print(confusion_matrix(single_test_y, single_y_pred))
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D, concatenate, Dropout, Flatten

model_path = '/content/drive/MyDrive/Datasets/first_model.h5'
model = tf.keras.models.load_model(model_path)
print(classification_report(single_test_y, single_y_pred))

4/4 [==============================] - 0s 97ms/step
(121, 2)
(121,)


ValueError: ignored

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D, concatenate, Dropout, Flatten
from tensorflow.keras.applications.inception_v3 import InceptionV3

model_path = '/content/drive/MyDrive/Datasets/first_model.h5'
model = tf.keras.models.load_model(model_path)

input_layer = Input(shape=(280, 280, 3))

base_model = InceptionV3(include_top=False, weights='imagenet', input_shape=(280,280,3))
for layer in base_model.layers:
    layer.trainable = False

x2 = base_model(input_layer)
x2 = ... # Inception 모델 구성
x2 = Dense(4, activation='relu')(x2) # 새로운 Dense 레이어

# 기존 모델과 Inception 모델을 연결하여 최종 출력을 만듦
x = ... # 기존 모델의 출력
x = Concatenate()([x, x2]) # 기존 모델의 출력과 Inception 모델의 출력 연결
x = Dense(4, activation='relu')(x)
output_layer = Dense(2, activation='sigmoid')(x)

model = Model(inputs=input_layer, outputs=output_layer)

TypeError: ignored

### (2) Transfer Learning
- **세부요구사항**
    * VGG16 모델은 1000개의 클래스를 분류하는 데 사용된 ImageNet 데이터셋을 기반으로 사전 학습된 가중치를 가지고 있습니다. 
        * 따라서 이 모델은 이미지 분류 문제에 대한 높은 성능을 보입니다.
        * 이 모델은 보통 전이학습(transfer learning)에서 기본적으로 사용되며, 특히 대규모 데이터셋이 없을 때는 기본 모델로 사용되어 fine-tuning을 수행합니다.
    * VGG16 함수로 부터 base_model 저장


In [30]:
from tensorflow.keras.applications import VGG16

#### 1) VGG16 불러와서 저장하기
* include_top=False로 설정하여 분류기를 제외하고 미리 학습된 가중치 imagenet을 로드합니다.
* .trainable을 True로 설정하여 모델의 모든 레이어들이 fine-tuning에 대해 업데이트되도록 합니다.


In [31]:
# base_model = VGG16(                 )
from tensorflow.keras.applications import VGG16

# VGG16 모델 불러오기
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(280, 280, 3))

# 모든 레이어가 fine-tuning에 대해 업데이트되도록 trainable 설정
for layer in model.layers:
    layer.trainable = True


58889256/58889256 [==============================] - 0s 0us/step


#### 2) VGG16과 연결한 구조 설계
* VGG16을 불러와서 Flatten, Dense 등으로 레이어 연결하기

### 모델 불러오기


In [104]:
model_path='/content/drive/MyDrive/Datasets/Lenet(0.87).h5'
model = tf.keras.models.load_model(model_path)

In [106]:
model_path='/content/drive/MyDrive/Datasets/Lenet(0.87).h5'
base_model = tf.keras.models.load_model(model_path)

# VGG16 모델 정의 (include_top=False로 설정하여 fully connected layer 제외)
vgg16 = tf.keras.applications.VGG16(weights='imagenet', include_top=False, input_shape=(280, 280, 3))

x = vgg16.output
x = Flatten()(x)
x = Dense(512, activation='relu')(x)
predictions = Dense(2, activation='sigmoid')(x)


new_model = tf.keras.models.Model(inputs=vgg16.input, outputs=predictions)

for layer in vgg16.layers:
    layer.trainable = False

for layer in vgg16.layers[:-100]:
    layer.trainable = False
for layer in vgg16.layers[-100:]:
    layer.trainable = True

new_model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

history = new_model.fit(x_train, y_train, epochs = 10000, verbose = 1, callbacks = [es], validation_data =(x_val,y_val))


Epoch 1/10000
13/13 [==============================] - 12s 663ms/step - loss: 604.9583 - accuracy: 0.5644 - val_loss: 0.6967 - val_accuracy: 0.4792
Epoch 2/10000
13/13 [==============================] - 8s 637ms/step - loss: 0.6725 - accuracy: 0.6521 - val_loss: 0.6928 - val_accuracy: 0.5833
Epoch 3/10000
13/13 [==============================] - 8s 642ms/step - loss: 0.6503 - accuracy: 0.6340 - val_loss: 1.1391 - val_accuracy: 0.5208
Epoch 4/10000
13/13 [==============================] - 8s 651ms/step - loss: 0.5705 - accuracy: 0.7191 - val_loss: 0.5692 - val_accuracy: 0.7292
Epoch 5/10000
13/13 [==============================] - 9s 659ms/step - loss: 0.5871 - accuracy: 0.7242 - val_loss: 0.9830 - val_accuracy: 0.5521
Epoch 6/10000
13/13 [==============================] - 8s 649ms/step - loss: 0.7113 - accuracy: 0.4948 - val_loss: 0.6161 - val_accuracy: 0.6979
Epoch 7/10000
13/13 [==============================] - 8s 644ms/step - loss: 0.5867 - accuracy: 0.7474 - val_loss: 0.6950 - val

In [72]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = new_model.predict(x_test)
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)
print(confusion_matrix(single_test_y, single_y_pred))
print(classification_report(single_test_y, single_y_pred))

4/4 [==============================] - 1s 214ms/step
(121, 2)
(121,)
[[60  0]
 [11 50]]
              precision    recall  f1-score   support

           0       0.85      1.00      0.92        60
           1       1.00      0.82      0.90        61

    accuracy                           0.91       121
   macro avg       0.92      0.91      0.91       121
weighted avg       0.92      0.91      0.91       121



In [42]:
single_y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0])

## 이건 인셉션

In [107]:
from tensorflow.keras.applications.inception_v3 import InceptionV3

# load the pre-trained InceptionV3 model without the top layer (include_top=False)
inception = InceptionV3(weights='imagenet', include_top=False, input_shape=(280, 280, 3))

# freeze the pre-trained layers
for layer in inception.layers:
    layer.trainable = False

# add custom layers on top of the pre-trained model
x = inception.output
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
predictions = tf.keras.layers.Dense(2, activation='sigmoid')(x)

# create the new model
new_model = tf.keras.models.Model(inputs=inception.input, outputs=predictions)

for layer in inception.layers[:-100]:
    layer.trainable = False
for layer in inception.layers[-100:]:
    layer.trainable = True

# compile the new model
new_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# train the new model
history = new_model.fit(x_train, y_train, epochs=10000, verbose=1, callbacks=[es], validation_data=(x_val,y_val))

Epoch 1/10000
13/13 [==============================] - 17s 295ms/step - loss: 0.3572 - accuracy: 0.8840 - val_loss: 0.6838 - val_accuracy: 0.9583
Epoch 2/10000
13/13 [==============================] - 2s 174ms/step - loss: 0.0430 - accuracy: 0.9845 - val_loss: 6.8309 - val_accuracy: 0.8125
Epoch 3/10000
13/13 [==============================] - 2s 174ms/step - loss: 0.0077 - accuracy: 0.9974 - val_loss: 6.5011 - val_accuracy: 0.8333
Epoch 4/10000
13/13 [==============================] - 2s 179ms/step - loss: 0.0348 - accuracy: 0.9923 - val_loss: 3.5796 - val_accuracy: 0.9167
Epoch 5/10000
13/13 [==============================] - 2s 175ms/step - loss: 0.0635 - accuracy: 0.9768 - val_loss: 4.7763 - val_accuracy: 0.9271
Epoch 6/10000
13/13 [==============================] - 2s 173ms/step - loss: 0.0546 - accuracy: 0.9923 - val_loss: 0.2599 - val_accuracy: 0.9583
Epoch 7/10000
13/13 [==============================] - 3s 200ms/step - loss: 0.0851 - accuracy: 0.9742 - val_loss: 0.6393 - val_a

In [108]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = new_model.predict(x_test)
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)
print(confusion_matrix(single_test_y, single_y_pred))
print(classification_report(single_test_y, single_y_pred))

4/4 [==============================] - 2s 117ms/step
(121, 2)
(121,)
[[59  1]
 [ 6 55]]
              precision    recall  f1-score   support

           0       0.91      0.98      0.94        60
           1       0.98      0.90      0.94        61

    accuracy                           0.94       121
   macro avg       0.94      0.94      0.94       121
weighted avg       0.95      0.94      0.94       121



## EfficientNet 

In [111]:
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.keras.layers import Dense, Flatten, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# EfficientNet V2 모델 불러오기
efficientnet = "https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet1k_s/feature_vector/2"
feature_extractor = hub.KerasLayer(efficientnet, input_shape=(280,280,3))

# 입력층 정의하기
input_layer = Input(shape=(280, 280, 3))

# 새로운 층 추가하기
x = feature_extractor(input_layer)
x = Flatten()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(2, activation='sigmoid')(x)

# 모델 생성하기
new_model = Model(inputs=input_layer, outputs=predictions)

# EfficientNet V2 모델 동결하기
feature_extractor.trainable = False


# 모델 컴파일하기
new_model.compile(optimizer=Adam(lr=0.0001), loss='binary_crossentropy', metrics=['accuracy'])

# 모델 학습하기
history = new_model.fit(x_train, y_train, epochs = 10000, verbose = 1, callbacks = [es], validation_data =(x_val,y_val))

AttributeError: ignored

In [110]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = new_model.predict(x_test)
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)
print(confusion_matrix(single_test_y, single_y_pred))
print(classification_report(single_test_y, single_y_pred))

4/4 [==============================] - 3s 199ms/step
(121, 2)
(121,)
[[58  2]
 [ 6 55]]
              precision    recall  f1-score   support

           0       0.91      0.97      0.94        60
           1       0.96      0.90      0.93        61

    accuracy                           0.93       121
   macro avg       0.94      0.93      0.93       121
weighted avg       0.94      0.93      0.93       121



## ResNet


In [112]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

model_path='/content/drive/MyDrive/Datasets/Lenet(0.87).h5'
base_model = tf.keras.models.load_model(model_path)

# VGG16 모델 정의 (include_top=False로 설정하여 fully connected layer 제외)
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(280, 280, 3))

x = base_model.output
x = Flatten()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(2, activation='sigmoid')(x)


model = Model(inputs=base_model.input, outputs=predictions)

# 기존 모델 동결하기
for layer in base_model.layers:
    layer.trainable = False

for layer in base_model.layers[:-100]:
    layer.trainable = False
for layer in base_model.layers[-100:]:
    layer.trainable = True

new_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = new_model.fit(x_train, y_train, epochs = 10000, verbose = 1, callbacks = [es], validation_data =(x_val,y_val))


Epoch 1/10000
13/13 [==============================] - 16s 363ms/step - loss: 0.3597 - accuracy: 0.8196 - val_loss: 0.2218 - val_accuracy: 0.9167
Epoch 2/10000
13/13 [==============================] - 3s 236ms/step - loss: 0.1059 - accuracy: 0.9716 - val_loss: 0.2097 - val_accuracy: 0.9271
Epoch 3/10000
13/13 [==============================] - 3s 226ms/step - loss: 0.0461 - accuracy: 0.9897 - val_loss: 0.2093 - val_accuracy: 0.9271
Epoch 4/10000
13/13 [==============================] - 3s 232ms/step - loss: 0.0236 - accuracy: 0.9948 - val_loss: 0.1929 - val_accuracy: 0.9167
Epoch 5/10000
13/13 [==============================] - 3s 233ms/step - loss: 0.0181 - accuracy: 1.0000 - val_loss: 0.2087 - val_accuracy: 0.9479
Epoch 6/10000
13/13 [==============================] - 3s 234ms/step - loss: 0.0082 - accuracy: 1.0000 - val_loss: 0.2510 - val_accuracy: 0.9271
Epoch 7/10000
13/13 [==============================] - 3s 231ms/step - loss: 0.0059 - accuracy: 1.0000 - val_loss: 0.2220 - val_a

In [114]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = new_model.predict(x_test)
y_pred.shape
single_y_pred = y_pred.argmax(axis=1)
single_y_pred.shape
print(y_test.shape)
single_test_y = y_test.argmax(axis=1)
print(single_test_y.shape)
print(confusion_matrix(single_test_y, single_y_pred))
print(classification_report(single_test_y, single_y_pred))

4/4 [==============================] - 2s 204ms/step
(121, 2)
(121,)
[[58  2]
 [ 6 55]]
              precision    recall  f1-score   support

           0       0.91      0.97      0.94        60
           1       0.96      0.90      0.93        61

    accuracy                           0.93       121
   macro avg       0.94      0.93      0.93       121
weighted avg       0.94      0.93      0.93       121



#### 3) 학습
- **세부요구사항**
    - 모델 학습 과정에 알맞은 보조 지표를 사용하세요.
    - 데이터
        * Image Generator를 연결하거나
        * 기존 train, validation 셋을 이용해도 됩니다.
        - Early Stopping을 반드시 사용하세요.
        - 최적의 가중치를 모델에 적용하세요.

#### 4) 성능 평가